### ISSUE TITLE
Visual selection going up

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#773] opened 2015-07-15 14:35 UTC
There seems to be a bug that when you try to select upwards, it doesn't work.

Steps:
    1) Go to line 2 or higher
    2) Enter command mode
    3) Hold shift+v
    4) Hit the up key

You'll see that the selection disappears.

**Comment by jacekkopecky** [comment] 2015-07-15 15:48
I struggle to reproduce this. In step 3, by writing "hold", do you mean "keep holding shift when you hit <up> step 4", by any chance?

**Comment by smaili** [comment] 2015-07-15 15:50
Yes that's exactly what I mean.

**Comment by jacekkopecky** [comment] 2015-07-15 15:58
Ah, that explains it. When you hit `shift-v`, the whole line is selected, and the cursor is actually on the next line. You can try it by making the cursor in visual mode visible with this style in your `.atom/styles.less`: 
```
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &          // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      border: none;
      border-left: 6px solid #29ff2f;
      left: -3px;
      z-index: -1;
      visibility: visible;
      opacity: 1;
      background: none;
    }
  }
}
```
When you then press `shift-up`, it's (at the moment) the normal Atom selection movement, not a vim-mode movement, so you move the cursor to the beginning of the selection and thus the selection is gone.

The issue might become: should vim-mode implement `shift-arrow` movements as { start visual mode if not there yet, perform normal vim movement } ?

**Comment by smaili** [comment] 2015-07-15 16:02
But here's the thing, once you go into visual mode, shouldn't `shift+up` be treated as a vim-mode movement?  It feels strange that if I'm on a line, select it in visual mode, and go up, suddenly it's gone, but if I'm on that same line, select it in visual mode, and go down, both the initial line and next line are selected.

**Comment by jacekkopecky** [comment] 2015-07-15 16:11
Yes, vim-mode could handle shift-arrow movements. That's a valid issue, I'd say.

I'm curious and hope you don't mind me asking - what makes you hold the shift for the `up` movement, after a `shift-v`? If you press the `up` arrow without shift, it behaves as expected in vim. Alternatively, in command mode, if you press `shift-cursor`, it's doing normal non-vim selection, moving vim-mode into visual (characterwise) automatically.

**Comment by smaili** [comment] 2015-07-15 16:17
Don't mind at all :)

That's how visual selection works in MacVim.  In MacVim, if you press `up` without `shift` once in visual mode it will exit out, it only selects if you hold `shift` while you press `up`.  Which to me is more intuitive because we're usually accustomed to holding shift whenever you want to select text.  It also gives the nice benefit of quickly getting out of visual mode without having to reach for the `esc` key :)

**Comment by jacekkopecky** [comment] 2015-07-15 16:43
Ah, interesting, my MacVIM does not exit visual mode when I press `up` or any other arrow key without a `shift`. Would you then also want atom vim-mode to exit visual mode when `up` is pressed without `shift`?

**Comment by smaili** [comment] 2015-07-15 16:49
For me personally, it'd be nice, but if it's something others would protest then I'm okay with it :+1:

**Comment by lee-dohm** [comment] 2018-04-05 17:18
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:18 UTC
