### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by patrickmedaugh** [atom/vim-mode#646] opened 2015-04-30 18:09 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.43.0
### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Users/pmedaugh/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /Users/pmedaugh/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/Users/pmedaugh/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/Users/pmedaugh/.atom/packages/vim-mode/lib/vim-state.coffee:209:18)
  at atom-text-editor.commands.(anonymous function) (/Users/pmedaugh/.atom/packages/vim-mode/lib/vim-state.coffee:192:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
  3x -0:20.8 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:20.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:19.9 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  6x -0:19.9 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:07.3 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:07.3 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.8 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.8 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.2 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.4 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:03.3 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.1 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.5 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:00.4 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.1 vim-mode:delete-to-last-character-of-line (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.9.0
seti-ui, v0.6.3
vim-mode, v0.43.0

# Dev
No dev packages
```

**Comment by djpowers** [comment] 2015-05-01 14:15
Just encountered this error myself:

[Enter steps to reproduce below:]

1. I was using the "Reveal Active File" keyboard shortcut, but I'm not sure that that had anything to do with it. I didn't notice if it actually selected the file in the tree view when I noticed the error message.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.45.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Users/dpowers/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /Users/dpowers/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/Users/dpowers/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/Users/dpowers/.atom/packages/vim-mode/lib/vim-state.coffee:207:18)
  at atom-text-editor.commands.(anonymous function) (/Users/dpowers/.atom/packages/vim-mode/lib/vim-state.coffee:190:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -9:27 core:copy (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  4x -9:25.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.4.0 tree-view:reveal-active-file (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:08.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:07.7.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:07.7.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.5.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.5.0 tree-view:toggle-focus (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.5.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.0 tree-view:reveal-active-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.2.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.7.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:02.7.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.3.0 vim-mode:mark (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:01.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-scss-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.1
color-picker, v1.7.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-erb, v0.1.0
linter-jshint, v0.1.2
linter-ruby, v0.1.4
minimap, v4.8.0
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-05-13 14:00
Noticed another report for this in https://github.com/atom/vim-mode/issues/663.

**Comment by chrislovecnm** [comment] 2017-07-20 01:00
Any work arounds for this?  Quite annoying :(

**Comment by winstliu** [comment] 2017-07-20 05:16
@chrislovecnm this package has been deprecated.  I would recommend uninstalling this and installing the excellent [vim-mode-plus](https://atom.io/packages/vim-mode-plus) package instead.

**Comment by lee-dohm** [comment] 2018-04-05 17:32
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:32 UTC
Labels: uncaught-exception
