### ISSUE TITLE
Failed to load the vim-mode package

### ISSUE THREAD

**Issue by qiulin** [atom/vim-mode#892] opened 2015-10-15 08:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.61.0

### Stack Trace

Failed to load the vim-mode package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\秋林\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\秋林\.atom\packages\vim-mode\lib\vim-mode.coffee:1:37)
    at Object.<anonymous> (C:\Users\秋林\.atom\packages\vim-mode\lib\vim-mode.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\秋林\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
javascript-snippets, v1.0.0
language-javascript-jsx, v0.3.7
relative-numbers, v0.2.2
vim-mode, v0.61.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-15 12:13
Duplicate of atom/atom#8891, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-15 12:13 UTC
