### ISSUE TITLE
is there any way to use ":" commands, eg, ":w" to write?

### ISSUE THREAD

**Issue by trailsandtribulations** [atom/vim-mode#588] opened 2015-03-24 06:08 UTC
is the any way to use ":" commands, eg, ":w" to write?

for me, having to cntl-s to save is counter-intuitive to the vim mentality

**Comment by maxbrunsfeld** [comment] 2015-03-24 19:28
This is a duplicate of #554. See the [ex-mode](https://atom.io/packages/ex-mode) package.

**Closed by maxbrunsfeld** 2015-03-24 19:28 UTC
