### ISSUE TITLE
Repetitive visual-mode block operations

### ISSUE THREAD

**Issue by opichals** [atom/vim-mode#246] opened 2014-05-15 13:19 UTC
Steps in vim:
- Mark a few lines using visual mode
- Indent using '>'
- Indent the whole block again using '.'

Atom appears to forget the block and rather just indents the cursor line at the moment

Atom Version 0.95.0 (0.95.0)

**Comment by maxbrunsfeld** [comment] 2015-01-08 06:06
I think this works now. Let me know if you still have problems with it.

**Comment by techniq** [comment] 2015-01-08 17:23
@maxbrunsfeld - Doing the steps in the original report are still an issue (make a visual selection, indent, then press `.` to indent again).  If I escape visual mode after indenting, pressing `.` to repeat the indention works.

**Comment by maxbrunsfeld** [comment] 2015-01-08 17:26
@techniq thanks, I see. So currently, `.` is not bound in visual mode. Do you all think that the proper solution would be to add a `.` binding in visual mode?

**Comment by techniq** [comment] 2015-01-08 19:04
@maxbrunsfeld - I think adding the binding would be right, but others might be better to chime in.

**Comment by james147** [comment] 2015-01-08 19:12
Note that Vim's default behaviour for visual indent is to exit visual mode
straight away and . then repeats the indent for the number of lines that
where selected starting at the cursor.

**Comment by techniq** [comment] 2015-01-08 20:20
I think adhering to Vim's default behavior would be best.  It's been a while since I've used Vim directly (used Sublime with vintage for a while before moving over to Atom).  Although staying in visual mode would allow repeated indenting with `>>` (or back with `<<`), instead of the initial `>>` or `<<` and then repeating the indention with `.`.  If you over indented with repeat, you'd have to restore your selection, and it currenlty looks like `gv` doesn't work with vim-mode to restore the last selection.

**Comment by maxbrunsfeld** [comment] 2015-01-08 21:08
Yeah, I actually like the fact that it stays in visual mode right now; it's kind of convenient. That said, I'm open to changing it to be more like vim if it's the only way to make the repeating use case work.

**Comment by techniq** [comment] 2015-01-08 22:13
If adding the `.` binding in visual mode works for others, I say that would
be the way to go.

**Comment by masukomi** [comment] 2015-01-09 12:26
Personally i *hate* vim's default behavior in this case. I had to go and figure out how to make it stop exiting visual mode every time I indented because it was driving me nuts. So, while I agree with folks about making vim's default behavior the default it'd be really, *really* nice is you had the option to stay in visual mode after performing an operation in it.

**Comment by bronson** [comment] 2015-05-21 07:38
I agree 100%.  I think Vim got this wrong.  Would love to see vim-mode stay in visual mode.

**Comment by flannelhead** [comment] 2015-07-08 05:42
It should be also noted that not adhering to vim's default behaviour here also breaks undoing block operations with 'u'. Steps to reproduce:

* Mark some lines in visual mode
* Indent with '>'
* Press 'u'

'u' is supposed to undo the indentation, which is what it does in vim. Personally, I'd prefer using '.' and 'u' for repeating and undoing operations on visual blocks. Ideally, the behaviour should be configurable as there are clearly two opinions about it.

**Comment by bronson** [comment] 2015-07-08 18:55
I take back my comment.  While I *personally* would like to see the visual selection stay, I also think that would be too big a departure.  vim-mode is all about providing a familiar finger-feel.

So, my opinion: I would love to see it work like Vim.  Then, if anybody still cares, we can start discussing how to provide the alternative behavior in another issue.

@masukomi 
> I had to go and figure out how to make it stop exiting visual mode every time I indented because it was driving me nuts.

How did you do that?

**Comment by maxbrunsfeld** [comment] 2015-07-08 19:09
> not adhering to vim's default behaviour here also breaks undoing block operations with 'u'.

Thanks for pointing that out @flannelhead. I can see how that sequence would be an important part of someone's muscle memory.

I think we should make it work like vim. If you want to indent lines and stay in visual mode, you can always use Atom's built-in indentation bindings, `Tab` and `Shift-Tab`, or `cmd-]` and `cmd-[`. I'd definitely merge a PR changing this. It would basically amount to reverting this previous PR: https://github.com/atom/vim-mode/pull/368/files.

**Comment by flannelhead** [comment] 2015-07-08 19:52
@maxbrunsfeld I'd be happy to do it, I'll hopefully have time for that in the weekend!

Overall, I think the way to go regarding almost any behaviour in vim-mode is to copy vim's default behaviour. If someone wants to change it, they can do it with a little script just as it would be done in vim (and especially those more familiar with JS/CS than Vimscript will be happy).

**Comment by bronson** [comment] 2015-07-08 20:49
oop, sorry @flannelhead.  I was halfway done when you commented.

**Comment by flannelhead** [comment] 2015-07-08 21:04
@bronson No problem, thank you for doing it!

**Comment by bronson** [comment] 2015-07-08 21:08
Happy to.  It's in vim-mode-next if anyone wants to try it out.

**Comment by chibicode** [comment] 2015-07-10 18:20
Adding to what @bronson said, anyone looking to repeat indenting in visual mode can add this their `keymap.cson`:

```cson
'atom-text-editor.vim-mode.visual-mode':
  '>': 'editor:indent-selected-rows'
  '<': 'editor:outdent-selected-rows'
```

**Comment by lee-dohm** [comment] 2018-04-05 17:37
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:37 UTC
Labels: bug
