### ISSUE TITLE
Uncaught TypeError: poppedOperation.execute is not a function

### ISSUE THREAD

**Issue by coforfe** [atom/vim-mode#897] opened 2015-10-26 00:26 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.61.0
### Stack Trace

Uncaught TypeError: poppedOperation.execute is not a function

```
At /Users/COF/.atom/packages/vim-mode/lib/vim-state.coffee:279

TypeError: poppedOperation.execute is not a function
    at VimState.module.exports.VimState.processOpStack (/Users/COF/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.pushOperations (/Users/COF/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at SearchViewModel.ViewModel.confirm (/Users/COF/.atom/packages/vim-mode/lib/view-models/view-model.coffee:11:15)
    at SearchViewModel.module.exports.SearchViewModel.confirm (/Users/COF/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:41:5)
    at SearchViewModel.confirm (/Users/COF/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:1:1)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (/Users/COF/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:45:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
```
### Commands

```
     -0:08.2.0 vim-mode:search (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
compare-files, v0.6.2
language-r, v0.3.0
pigments, v0.18.0
vim-mode, v0.61.0

# Dev
No dev packages
```

**Comment by kamek-pf** [comment] 2015-11-18 16:04
This happens when I try to `dt<`.
It works as expected, but the alert shows up.

**Comment by uiii** [comment] 2016-03-25 09:26
**vim-mode 0.65.0** the issue is happening again when I delete text using `dt'` or `dt<`
```
Uncaught TypeError: poppedOperation.execute is not a function
/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:816
```

However, the deletion works but the error notification is really annoying.

**Comment by eric-burel** [comment] 2016-04-20 08:03
I reproduced the same issue with `df}`, same as @uiii it actually deletes the text but throw an error notification.
**Vim-mode 0.65.0
Atom 1.6.0**

**Comment by uiii** [comment] 2016-05-27 06:46
I don't have this issue anymore with **Vim-mode v0.65.1** and **Atom 1.7.4**

**Comment by lbeeon** [comment] 2016-11-14 06:33
I have the same problem. Reproduced the issue with 'r' in visual mode.
Atom 1.12.2
Vim-mode 0.65.1
OS macOS Sierra 10.12.1

**Comment by lee-dohm** [comment] 2018-04-05 16:58
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:58 UTC
Labels: uncaught-exception
