### ISSUE TITLE
Delete word (dw) should not delete line break

### ISSUE THREAD

**Issue by dsandstrom** [atom/vim-mode#550] opened 2015-03-05 19:19 UTC
If I have a line of code and I try to delete the last word, `dw` joins the lower line to the current line.  I would expect more of the behavior that `de` provides.  It deletes the word, but doesn't join the lower line.

```
test test
nope
```

becomes

```
test nope
```

I would expect

```
test
nope
```

**Comment by maxbrunsfeld** [comment] 2015-03-05 20:14
Yeah, I think I introduced this regression during the push to get multi-cursors working everywhere. The `w` motion behaves differently in visual and operator-pending modes, so we would need to differentiate between modes in [`MoveToNextWord::moveCursor`](https://github.com/atom/vim-mode/blob/master/lib/motions/general-motions.coffee#L215). I'd love to merge a PR fixing this.

**Comment by dsandstrom** [comment] 2015-03-05 21:53
@maxbrunsfeld Just to confirm, visual and command mode `w` should wrap.  However, operator-pending mode `w` should not wrap (eg. `dw` and `d1000w`).

**Comment by maxbrunsfeld** [comment] 2015-03-05 22:06
@dsandstrom right. Thanks for clarifying.

**Comment by dsandstrom** [comment] 2015-03-09 20:50
If there is only one word left, `dw` should delete to the end of the line and not join the next line.  However, I think `dw` should wrap if you are at the end of the line.   That is probably what you wanted, but I just want to be clear.

I wasn't able to spend a lot of time on this over the weekend, but I did get something working.  For my solution, I had to use a modified `Cursor::wordRegExp`.  I need to add `$` to the normal one.  Should I make a PR to add a optional end of line to Atom's cursor or use a custom `@wordRegExp` that this package uses?  I don't think you can add to RegExp's together.

**Comment by huanzhang** [comment] 2015-05-20 14:09
+1

**Comment by ssfrr** [comment] 2015-07-02 04:46
:+1:

**Comment by bronson** [comment] 2015-07-03 08:38
I disagree that dw should wrap if you're at the end of the line.  Vim doesn't.  It just deletes the last character on the line.

I absolutely agree that this needs to be fixed.  It affects me many times during the day.

**Comment by dsandstrom** [comment] 2015-07-07 18:06
@bronson I agree now, we should match vim as much as possible.  That is what I was referring to in #581, but you said it more succinctly.
> In vim, I noticed that dw also deletes the preceding space, which this PR doesn't fix.

**Comment by brandall10** [comment] 2015-08-12 13:36
Any movement on this?  Coming from VIM to Atom recently, this is probably my #1 gripe.  I've trained myself to do a d$ for the last word as a workaround, but still muscle memory gets the best of me at times.

**Comment by jacekkopecky** [comment] 2015-08-13 10:27
Hmm, this one has fallen through the cracks. @dsandstrom do you have any spare cycles to update #581? If you don't, I can clone that PR and finish it.

**Comment by dsandstrom** [comment] 2015-08-13 17:13
I should have some time this weekend.

**Comment by brandall10** [comment] 2015-08-13 17:15
@dsandstrom 

You are my hero.  Much appreciated.

**Comment by dsandstrom** [comment] 2015-08-16 22:25
I submitted a PR (atom/atom#8403) to make this change simpler in vim-mode.  If it's merged, I will update #581 or submit a new one.  If it's rejected, I will clean up #581.

**Comment by sanbornm** [comment] 2015-08-24 17:00
:+1:

**Comment by charlesswartz** [comment] 2015-09-26 18:17
Any progress on this? It can be supremely frustrating at times.

**Comment by soloradish** [comment] 2016-01-01 10:09
any update?

**Comment by thefron** [comment] 2016-07-11 03:06
Is there any progress here? This still annoys me.

**Comment by Wiebelt** [comment] 2016-07-11 08:00
@thefron This is fixed in [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus). See also [the reference](https://github.com/t9md/atom-vim-mode-plus/issues/150) above your comment.

**Comment by thefron** [comment] 2016-07-13 03:43
@Wiebelt vim-mode-plus works fine to me. Thank you for letting me know!

**Comment by jayd3e** [comment] 2016-10-18 19:44
This also annoys me, just to chime in.  Downloading vim-mode-plus.

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: bug
