### ISSUE TITLE
changing the insert mode error

### ISSUE THREAD

**Issue by jaemyoun** [atom/vim-mode#626] opened 2015-04-17 01:11 UTC
After inputting 'o' to enter the insert mode, I inputted 'escape' to enter the command mode. After that, the key binding don't work. Given I input any keys, the mode is changed to the visual mode.

My vim-mode's version is 0.44.

ps. This occurred inserting Korean language.

**Comment by bronson** [comment] 2015-05-21 07:03
I can't reproduce this.  Does it only occur when inserting Korean?

**Comment by jaemyoun** [comment] 2015-05-26 17:08
Yes, only inserting Korean.

**Comment by lee-dohm** [comment] 2018-04-05 17:32
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:32 UTC
