### ISSUE TITLE
c,v,d inside character doesnt works

### ISSUE THREAD

**Issue by cocodrino** [atom/vim-mode#403] opened 2014-09-19 16:41 UTC
Hi..I'm trying to change content inside some symbol c i ( or select v i " but seems not works as expected inside atom vim, is possible fix it??

**Comment by maxbrunsfeld** [comment] 2015-01-08 05:02
All of these work now as far as I can tell. Can you upgrade to the latest Atom and the latest `vim-mode` and see if these problems still occur?

**Comment by cocodrino** [comment] 2015-01-08 05:42
nope, seems not works,I've atom 0.165.0 and vim mode 0.25

test code
{blah ( blah b|lah ) $%%$ }
                     cursor here

vi{  => {blah ( blah b
vi(  => nothing selected

" asdasd|as"

va"=>nothing selected
vi" => nothing selected

please let me know if it works with you...I can try reinstall the package again...

**Comment by maxbrunsfeld** [comment] 2015-01-08 06:01
Does the pipe character represent the cursor? If so, yes all of these things work for me. Maybe post a gif?

**Comment by james147** [comment] 2015-01-08 10:59
Still does not work here 
atom: 0.168.0
vim-mode: 0.25.0

![snapshot1](https://cloud.githubusercontent.com/assets/171232/5661433/9264ca66-9723-11e4-9220-116e963fee45.png) `vi{` ![snapshot2](https://cloud.githubusercontent.com/assets/171232/5661435/9c639a7e-9723-11e4-8d1c-9e2569316b3c.png)

![dq1](https://cloud.githubusercontent.com/assets/171232/5661436/9c6589e2-9723-11e4-92bc-e96dca2dd202.png) `vi"` ![dq2](https://cloud.githubusercontent.com/assets/171232/5661434/9c616be6-9723-11e4-9357-6dd68d980e17.png)

![ab1](https://cloud.githubusercontent.com/assets/171232/5661483/275d6e48-9724-11e4-9ce2-b0713ccc51d8.png) `vi<` ![ab2](https://cloud.githubusercontent.com/assets/171232/5661484/27628298-9724-11e4-9de1-b932883f0dc0.png)

![br1](https://cloud.githubusercontent.com/assets/171232/5661513/8fbbf630-9724-11e4-9057-a723fa8c4e2d.png) `vi(` ![br2](https://cloud.githubusercontent.com/assets/171232/5661514/8fbc8fd2-9724-11e4-925a-8df551225448.png)

These two work as expected:
![sq1](https://cloud.githubusercontent.com/assets/171232/5661437/9c684bc8-9723-11e4-83fe-6d623f039bb8.png) `vi'` ![sq2](https://cloud.githubusercontent.com/assets/171232/5661438/9c68dac0-9723-11e4-9256-8b5299370382.png)

![sb1](https://cloud.githubusercontent.com/assets/171232/5661570/48a53dbe-9725-11e4-8376-23bd38c6f84e.png) `vi[` ![sb2](https://cloud.githubusercontent.com/assets/171232/5661571/48a98356-9725-11e4-9ca4-10d474df81b3.png)


The same thing happens for `[cdv][ia]X` but with the given action (ie d deletes the text rather then selecting it)

**Comment by james147** [comment] 2015-01-08 11:08
Note that outside characters also do not work ie `va"` should do the same as `vi"` but also select the `"`s: 

![out1](https://cloud.githubusercontent.com/assets/171232/5661686/7b926796-9726-11e4-97a4-67491434966a.png) `va"` actual: ![out2](https://cloud.githubusercontent.com/assets/171232/5661684/7b8e5e9e-9726-11e4-9268-5311ad702cf8.png) expected: ![out3](https://cloud.githubusercontent.com/assets/171232/5661685/7b915540-9726-11e4-8a36-cfe8d1998268.png)

**Comment by maxbrunsfeld** [comment] 2015-01-08 15:56
@james147 what keyboard layout are you using? Maybe this is a keymap issue.

**Comment by james147** [comment] 2015-01-08 16:51
The UK layout

**Comment by javaguirre** [comment] 2015-01-08 17:07
I have en_US, Atom 0.168, vim-mode 0.25 on GNU/Linux and `ci(` doesn't work nor `ci"` and I guess neither the others we reported before, I didn't have time to do more tests though, might it be an OS issue? related to having another package installed?

**Comment by maxbrunsfeld** [comment] 2015-01-08 17:22
@james147, @javaguirre could you report what the keybinding-resolver shows for each keystroke of `ci(`?

**Comment by javaguirre** [comment] 2015-01-08 17:36
when I press ci(

While pressing `ci`

![screenshot from 2015-01-08 18 32 32](https://cloud.githubusercontent.com/assets/488556/5667062/09119eb4-9765-11e4-97ab-ee5fce14b997.png)

after pressing `(`

![screenshot from 2015-01-08 18 34 07](https://cloud.githubusercontent.com/assets/488556/5667070/15e0d2a4-9765-11e4-97ae-12e950722302.png)

It's not resolving anything after ci, just stops.

**Comment by maxbrunsfeld** [comment] 2015-01-08 18:14
Ok, I think this is a keymap problem. To reduce it further, could you try adding this to your `keymap.cson`?

```coffee
'*':
  '[': 'application:about'
  ']': 'application:about'
  '(': 'application:about'
  ')': 'application:about'
  '<': 'application:about'
  '>': 'application:about'
  '"': 'application:about'
  "'": 'application:about'
```

With these mappings, all of these characters should cause the "About" dialog to appear. If it doesn't, could you open an issue on the [atom-keymap](https://github.com/atom/atom-keymap) repo?

**Comment by javaguirre** [comment] 2015-01-08 18:19
Adding that to `keymaps.cson` triggers the about dialog command as you said.

**Comment by maxbrunsfeld** [comment] 2015-01-08 18:28
@javaguirre, even the `(` key?

**Comment by javaguirre** [comment] 2015-01-08 18:33
Yes.

![screenshot from 2015-01-08 19 32 59](https://cloud.githubusercontent.com/assets/488556/5668102/2ec564c6-976d-11e4-91f7-d2b5170850c9.png)

**Comment by maxbrunsfeld** [comment] 2015-01-08 18:38
Does this key mapping work (with `vim-mode` disabled)?

```coffee
'*':
  'c i (': 'application:about'
```

**Comment by javaguirre** [comment] 2015-01-08 18:47
I think you are right, It's a keymap issue, If I disable the vim-mode and add only this new keymap, the keybinding-resolver stops at `ci` and treats the `(` as a new command without taking into account `ci`.

The command appears as option to be completed in the keybinding-resolver, but It doesn't work.

![screenshot from 2015-01-08 19 46 12](https://cloud.githubusercontent.com/assets/488556/5668300/1ef9bbd0-976f-11e4-9e00-2aae8855cf72.png)

**Comment by flannelhead** [comment] 2015-01-08 19:42
I think this is because to type '(' the actual keypress is shift + 9 (on a regular US PC keyboard). On my Linux system, shift seems to generate a separate keydown event before the event for the key 9. The only-shift event doesn't match to any binding, so the following '9' with modifier shift gets ignored.

**Comment by maxbrunsfeld** [comment] 2015-01-08 19:45
The key-map system *should* handle perform matching on keydown events for modifier keys like `shift`, but there must be a bug. It could be specific to linux.

**Comment by flannelhead** [comment] 2015-01-08 20:04
The problem is that the 'shift' key alone (before the actual key) generates an event. That interrupts matching the sequence 'i ('. I filed a bug about it to atom-keymap.

**Comment by bronson** [comment] 2015-05-21 08:16
This appears fixed...  worth closing?

**Comment by cocodrino** [comment] 2015-05-22 16:17
nope, it's not fixed yet (or at least I dunno the solution :D)

**Comment by cocodrino** [comment] 2015-05-22 16:18
nope, it's not fixed yet (or at least I dunno the solution :D)

**Comment by binarious** [comment] 2016-06-21 20:27
Any news on this? Running into this with `c i {` and `c i [` on a German Mac keyboard. `{` and `[` are typed via Alt + 8 or Alt + 5. The Key Binding Resolver only outputs `alt-8` after `c i {`. 
Characters typed with the Shift key do work (like `c i (` or `c i '`).
Any ideas?

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: more-information-needed
