### ISSUE TITLE
Command mode view causes errors

### ISSUE THREAD

**Issue by rstacruz** [atom/vim-mode#429] opened 2014-10-27 10:01 UTC
Pressing `r` or `/` gives off this error:

    Uncaught TypeError: undefined is not a function 
    vim-command-mode-input-view.coffee:63

It seems like `@editorContainer` is not available in *vim-command-mode-input-view.coffee*.

[source](https://github.com/atom/vim-mode/blob/master/lib/view-models/vim-command-mode-input-view.coffee#L63)

**Comment by maxbrunsfeld** [comment] 2015-01-08 04:59
@rstacruz can you upgrade to the latest Atom and `vim-mode` and report whether or not this still happens? Thanks.

**Comment by izuzak** [comment] 2015-09-09 13:41
Closing since this is super old, there were no reports from other users as far as I can tell, and no new information was provided in more than 6 months after we asked. 

@rstacruz Let us know if you can still reproduce this in Atom 1.0.11

**Closed by izuzak** 2015-09-09 13:41 UTC
Labels: more-information-needed, uncaught-exception
