### ISSUE TITLE
Link to create issues is broken

### ISSUE THREAD

**Issue by peterjeliot** [atom/vim-mode#484] opened 2015-01-11 01:14 UTC
When I have an error related to this plugin, it gives this link to create an issue: http://git.io/PccR7g

This link gives a 404 error.

**Comment by peterjeliot** [comment] 2015-01-11 01:15
![screen shot 2015-01-10 at 5 14 39 pm](https://cloud.githubusercontent.com/assets/491376/5693952/30d3c8f4-98ec-11e4-9c98-1032ac09ab1f.png)

Any bug related to the vim plugin gives this same broken link, I believe.

**Comment by peterjeliot** [comment] 2015-01-11 01:24
Interestingly, the link to 'report issue' under the package preferences page correctly links to https://github.com/atom/vim-mode/issues/new

**Comment by benogle** [comment] 2015-01-13 00:04
@peterjeliot when you get an error, can you pop open the dev tools and run 

```
document.querySelector('atom-notification.fatal').getIssueUrl()
```

That will output a collapsed string. Click on the string in the console, and paste it into this issue.

Dupe of https://github.com/atom/atom/issues/4933

**Comment by peterjeliot** [comment] 2015-01-14 04:09
That URL is correct (if a little garbled with the chosen title):

https://github.com/atom/bracket-matcher/issues/new?title=Uncaught%20TypeErr…6.0%0A%0A%23%20Dev%0ANo%20dev%20packages%0A%60%60%60%0A%0A/cc%20@atom/core

**Comment by benogle** [comment] 2015-01-14 19:03
That is unfortunately the truncated version. So the console apparently no longer expands the string on click. Try this:

```
atom.notifications.addWarning(document.querySelector('atom-notification.fatal').getIssueUrl(), {dismissable: true})
```

That will pop up a notification, and you can copy the url out of the notification.

**Comment by peterjeliot** [comment] 2015-01-14 20:14
Yep, it's a long one.

```
https://github.com/atom/bracket-matcher/issues/new?title=Uncaught%20TypeError:%20Cannot%20read%20property%20%27getScreenPosition%27%20of%20undefined&body=%5BEnter%20steps%20to%20reproduce%20below:%5D%0A%0A1.%20...%0A2.%20...%0A%0A**Atom%20Version**:%200.170.0%0A**System**:%20Mac%20OS%20X%2010.10.1%0A**Thrown%20From**:%20%5Bbracket-matcher%5D(https://github.com/atom/bracket-matcher)%20package,%20v0.67.0%0A%0A%23%23%23%20Stack%20Trace%0A%0AUncaught%20TypeError:%20Cannot%20read%20property%20%27getScreenPosition%27%20of%20undefined%0A%0A%60%60%60%0AAt%20/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1325%0A%0ATypeError:%20Cannot%20read%20property%20%27getScreenPosition%27%20of%20undefined%0A%20%20at%20TextEditor.module.exports.TextEditor.getCursorScreenPosition%20(/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1325:34)%0A%20%20at%20TextEditor.module.exports.TextEditor.isFoldedAtCursorRow%20(/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2585:44)%0A%20%20at%20BracketMatcherView.module.exports.BracketMatcherView.updateMatch%20(/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)%0A%20%20at%20/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26%0A%20%20at%20Emitter.module.exports.Emitter.emit%20(/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)%0A%20%20at%20/Applications/Atom.app/Contents/Resources/app/src/cursor.js:70:25%0A%20%20at%20Emitter.module.exports.Emitter.emit%20(/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)%0A%20%20at%20Marker.module.exports.Marker.destroyed%20(/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)%0A%20%20at%20/Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24%0A%20%20at%20Emitter.module.exports.Emitter.emit%20(/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:82:11)%0A%20%20at%20Marker.module.exports.Marker.destroy%20(/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)%0A%20%20at%20Marker.module.exports.Marker.destroy%20(/Applications/Atom.app/Contents/Resources/app/src/marker.js:62:25)%0A%20%20at%20Selection.module.exports.Selection.destroy%20(/Applications/Atom.app/Contents/Resources/app/src/selection.js:62:26)%0A%20%20at%20SnippetExpansion.module.exports.SnippetExpansion.setTabStopIndex%20(/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:120:21)%0A%20%20at%20SnippetExpansion.module.exports.SnippetExpansion.goToNextTabStop%20(/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:86:18)%0A%20%20at%20Object.module.exports.goToNextTabStop%20(/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:397:43)%0A%20%20at%20atom-text-editor.subscriptions.add.atom.commands.add.snippets:next-tab-stop%20(/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:56:25)%0A%20%20at%20CommandRegistry.module.exports.CommandRegistry.handleCommandEvent%20(/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)%0A%20%20at%20/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61%0A%20%20at%20KeymapManager.module.exports.KeymapManager.dispatchCommandEvent%20(/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)%0A%20%20at%20KeymapManager.module.exports.KeymapManager.handleKeyboardEvent%20(/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)%0A%20%20at%20HTMLDocument.module.exports.WindowEventHandler.onKeydown%20(/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)%0A%0A%60%60%60%0A%0A%23%23%23%20Commands%0A%0A%60%60%60%0A%20%20%20%20%20-0:18.2%20core:save%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:16.4%20vim-mode:move-down%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:16.0%20vim-mode:insert-below-with-newline%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:15.6%20editor:newline%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:14.0%20snippets:next-tab-stop%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:14.0%20snippets:expand%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:09.9%20vim-mode:activate-command-mode%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:05.0%20vim-mode:reset-command-mode%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:04.5%20vim-mode:move-down%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:03.9%20vim-mode:activate-insert-mode%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:03.4%20core:move-right%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:03.1%20snippets:next-tab-stop%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%20%20%20%20%20-0:00.0%20window:toggle-dev-tools%20(atom-text-editor.editor.vim-mode.insert-mode)%0A%60%60%60%0A%0A%23%23%23%20Config%0A%0A%60%60%60json%0A%7B%0A%20%20%22core%22:%20%7B%7D%0A%7D%0A%60%60%60%0A%0A%23%23%23%20Installed%20Packages%0A%0A%60%60%60coffee%0A%23%20User%0Aautocomplete-plus,%20v1.1.0%0Avim-mode,%20v0.26.0%0A%0A%23%20Dev%0ANo%20dev%20packages%0A%60%60%60%0A%0A/cc%20@atom/core
```

**Comment by benogle** [comment] 2015-01-20 22:54
Thanks for the link. Closing in favor of: https://github.com/atom/atom/issues/4933

**Closed by benogle** 2015-01-20 22:54 UTC
