### ISSUE TITLE
A

### ISSUE THREAD

**Issue by upq** [atom/vim-mode#1049] opened 2016-08-11 22:15 UTC
'A' which is suppoused to go to the end of the line and start insert mode
``` 'A': 'vim-mode:insert-after-end-of-line' ```
 goes one charecter before the line end.

**Comment by amfarrell** [comment] 2016-08-18 13:40
'a' which is supposed to start insert move with the cursor just after the current character fails at the end of the line. At the end of the line, it inserts the cursor before the current character. It works properly on all characters except the last one. Therefore, I suspect the issue is some code shared between these two bindings.

**Comment by amfarrell** [comment] 2016-08-18 13:44
This is a duplicate of #995 . Note that going to Atom > Preferences > Packages, searching vim-mode and hitting Disable, then hitting Enable causes this to work properly.

**Comment by 50Wliu** [comment] 2016-08-18 14:40
Thanks @amfarrell.

**Closed by 50Wliu** 2016-08-18 14:40 UTC
