### ISSUE TITLE
Tab in normal mode inserts a tab

### ISSUE THREAD

**Issue by holguinj** [atom/vim-mode#204] opened 2014-04-11 22:40 UTC
I think I was expecting it to fold (not sure if that's implemented yet), but it just inserted two space characters.

**Comment by mattsawyer77** [comment] 2015-02-24 18:01
I'm not sure if this is exactly the same issue, but I've noticed that when entering insert mode, then hitting tab, the cursor advances too far if there are trailing tab characters already on the line.

**Comment by romgrk** [comment] 2015-04-01 06:53
Same here. Seems to be that <Tab> is catched by editor:indent. I think it should be disabled by vim-mode on startup, or maybe just in normal mode.

**Comment by mattsawyer77** [comment] 2015-04-01 20:24
Any ETA on this? I'd argue that this is really a bug, not an enhancement. It's probably the most annoying aspect of working with vim-mode for me.

**Comment by bronson** [comment] 2015-05-21 09:20
vim just ignores tab in normal mode, right?  would the desired fix be to make vim-mode ignore tab too?

I can't seem to reproduce moving too far when hitting tab in insert mode...  Does it happen when vim-mode is the only 3rd party package enabled?

**Comment by tangledhelix** [comment] 2016-10-05 19:22
So far as I can tell, it doesn't move "too far," what it seems to be doing is matching whatever the current indent level is (based on the lines prior to it, and probably influenced by the indentation rules of the language you're editing).

In any case, I would agree Tab should be ignored. This is just doing shifts, the Vim way to do that is `>>` and `<<`, not Tab.

**Comment by blockloop** [comment] 2016-10-18 16:01
This is a bug because normal mode tab does nothing in real vim. I fixed with this custom key map.

```cson
'atom-text-editor.vim-mode.normal-mode':
  'tab': 'noop'
```

I don't know of `noop` is an actual atom command, but `unset!` looked to gave a weird behavior and seemed to tab out of the editor altogether. `noop` didn't throw any errors and it does nothing. Works for me.

**Comment by lee-dohm** [comment] 2018-04-05 17:37
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:37 UTC
Labels: enhancement
