### ISSUE TITLE
Automatically insert mode if there is a selection

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#748] opened 2015-07-08 21:27 UTC
Hi,

Coming from MacVim, one thing that was very handy for me was being able to select text, then once I type any character key it would automatically go into insert mode and replace the selected text with what I had typed.

Would it be possible to add this into the vim-mode package as well?

**Comment by bronson** [comment] 2015-07-09 01:05
I've never heard of this.  Is it a Vim plugin?

So, you would select some text, type `y` and, instead of yanking, the selection would be replaced by a letter y?  That doesn't sound terribly useful to me...  How would you change case / indent / surround / etc?

**Comment by bronson** [comment] 2015-07-09 01:06
Oh, first typing `c` (change) or `s` (substitute) will do what you want.

**Comment by msmaili** [comment] 2015-07-09 01:11
You'd be surprised how useful it is :)

I'm pretty sure it's not a plugin, it's the default behavior for MacVim.  Many times I find myself refactoring or pasting in text with only parts to replace, and the most intuitive way is to just select and start typing away.

I wasn't aware of the change/substitute but I'd still like to have this functionality because I'm sure I'm not the only Atom user coming from MacVim.  But if you don't feel it's worth having as the default functionality, what about having it be a configuration setting?  Maybe label it something along the lines of `Auto insert mode on selection typing`?  Kind of lengthy but gets the point across :)

**Comment by bronson** [comment] 2015-07-09 01:31
But MacVim doesn't work like that.  I just tried it -- select some text and hit 'y'.  The text gets yanked instead of getting replaced by a 'y'.  You must have configured it somehow.

If Vim worked like this, how would you change the case of the selection?  Or insert text before it, or any of the thousand other useful things Vim can do on selections?

**Comment by msmaili** [comment] 2015-07-09 01:40
Ahh, yes you're completely right Scott!  I didn't realize I had this in my vimrc file

```
source $VIMRUNTIME/mswin.vim
behave mswin
```

To be honest, I haven't yet run into a case I needed it.  May just be because I've grown so used to using the `mswin` behavior :)

**Comment by msmaili** [comment] 2015-07-09 01:42
But as I said, I would be okay with having it be a configuration setting rather than default behavior.  Since I now understand it's part of the `mswin` behavior, maybe that would be a more appropriate setting name?  That way, it also goes more inline with how it's done on MacVim, and any other behaviors from it that people would like to add, you can add it under this same setting rather than having to create a different setting name for it.  What do you think?

**Comment by bronson** [comment] 2015-07-09 02:07
It's OK, that happened to me earlier today: https://github.com/atom/vim-mode/pull/568#issuecomment-119359818

Sure, filing a feature request for 'mswin' makes sense.

If you feel adventurous, you might be able to reproduce that feature by mapping all keys in visual mode to `vim-mode:change`: https://github.com/atom/vim-mode/blob/master/keymaps/vim-mode.cson#L263-L268  That way you only have to play with your own keymap.

**Comment by t9md** [comment] 2015-07-21 07:43
My operation to change part of multi selection.
put cursor to `scanRange` and cmd-d(`find-and-replace:select-next`)  three times select three instance of `scanRange`, but problem is when I type `I` to enter Insert mode, cursor position won't be put where I want.

```coffeescript
    startOfTrailingWhitespace = [scanRange.end.row, scanRange.end.column - 1]
    @editor.scanInBufferRange /[ \t]+$/, scanRange, ({range}) ->
```

By using [vim-mode-visual-block](https://atom.io/packages/vim-mode-visual-block).
Operation for above case is `cmd-d` three times, then `ctrl-v` then `I` to put cursors to head of each selection.
Using this usage of visual-block mode is not there in original Vim but work perfectly.

Hope this solve some situation you have.

**Comment by jacekkopecky** [comment] 2015-07-21 11:15
In the situation like yours, I've been doing it like this:
 1. put cursor on `scanRange`
 2. press `cmd-d` three times
 3. press `<escape>` once - it will drop visual mode but it will keep the three cursors
 4. press `b` if you want to start inserting at the beginning of the word, nothing otherwise
 5. press `i` or `a` as appropriate to start editing

Multiple cursors rock!

I've also hacked together operations to add cursor below/above the current cursor, which has helped with some operations that in VIM I'd do with macros or visual selections. In `keymap.cson`:
```
'atom-text-editor':
  'cmd-down': 'jacek:add-cursor-down'
  'cmd-up': 'jacek:add-cursor-up'
```
In `init.coffee`:
```
atom.commands.add "atom-text-editor", "jacek:add-cursor-down", ->
  addCursorInDirection(1)

atom.commands.add "atom-text-editor", "jacek:add-cursor-up", ->
  addCursorInDirection(-1)

addCursorInDirection = (dir) ->
  editor = atom.workspace.getActiveTextEditor()
  cursor = editor.getLastCursor()
  coords = cursor.getBufferPosition()

  newcoords = { column: cursor.goalColumn || coords.column, row: coords.row + dir }
  newcursor = editor.addCursorAtBufferPosition(newcoords)

  newcursor.goalColumn = cursor.goalColumn || coords.column
```

**Comment by lee-dohm** [comment] 2018-04-05 17:27
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:27 UTC
Labels: enhancement
