### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by michaltaberski** [atom/vim-mode#924] opened 2015-11-17 10:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Users/michal/.atom/packages/vim-mode/lib/vim-state.coffee:276

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at TextEditor.module.exports.TextEditor.getScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2859:12)
    at Yank.execute (/Users/michal/.atom/packages/vim-mode/lib/operators/general-operators.coffee:182:5)
    at VimState.module.exports.VimState.processOpStack (/Users/michal/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/Users/michal/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/Users/michal/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at atom-text-editor.commands.(anonymous function) (/Users/michal/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:32 vim-mode:indent (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:31.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:30.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:29 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:24 vim-mode:move-to-start-of-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 21x -0:21 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:17.8.0 vim-mode:yank-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:16.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:15.4.0 vim-mode:yank-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:15 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:13.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:13 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -0:09.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.5.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.4.0 vim-mode:yank-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-jade, v0.3.0
emmet, v2.3.14
git-blame, v0.4.7
language-babel, v2.5.0
language-elm, v1.3.0
language-haml, v0.23.6
markdown-preview-opener, v0.1.1
nuclide-code-format, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-watcher, v0.0.32
react, v0.12.10
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-17 13:47
Duplicate of facebook/nuclide#246, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-17 13:47 UTC
