### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by amit-handa** [atom/vim-mode#586] opened 2015-03-21 13:36 UTC
[Enter steps to reproduce below:]
1. my kid was typing like a maniac and kept the keys pressed for a long time. Thats all I know.

**Atom Version**: 0.187.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.40.0
### Stack Trace

Uncaught RangeError: Invalid array length

```
At /home/gamihan/.atom/packages/vim-mode/lib/vim-state.coffee:249

RangeError: Invalid array length
  at Object._.times (/usr/share/atom/resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:1118:28)
  at MoveRight.moveCursor (/home/gamihan/.atom/packages/vim-mode/lib/motions/general-motions.coffee:153:7)
  at MoveRight.Motion.execute (/home/gamihan/.atom/packages/vim-mode/lib/motions/general-motions.coffee:35:8)
  at Repeat.Prefix.execute (/home/gamihan/.atom/packages/vim-mode/lib/prefixes.coffee:21:31)
  at VimState.module.exports.VimState.processOpStack (/home/gamihan/.atom/packages/vim-mode/lib/vim-state.coffee:252:23)
  at VimState.module.exports.VimState.processOpStack (/home/gamihan/.atom/packages/vim-mode/lib/vim-state.coffee:244:10)
  at VimState.module.exports.VimState.pushOperations (/home/gamihan/.atom/packages/vim-mode/lib/vim-state.coffee:213:8)
  at atom-text-editor.commands.(anonymous function) (/home/gamihan/.atom/packages/vim-mode/lib/vim-state.coffee:185:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -37:06.2 grammar-selector:show (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -35:52.6 editor:move-to-first-character-of-line (atom-text-editor.editor.mini)
     -30:15.1 vim-mode:move-to-mark (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -30:14.4 blur (atom-text-editor.editor.mini.is-focused)
  8x -30:10.7 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:10.2 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:10.2 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:10.2 editor:indent (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 13x -30:10.2 core:page-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 10x -30:09.4 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:08.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  8x -30:08.4 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:01.6 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -30:00.1 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.1
autocomplete-plus, v2.6.0
linter, v0.12.0
seti-syntax, v0.3.3
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment] 2015-03-21 16:53
I think this is a duplicate of #401; very large repeat counts (e.g. `1234123409875210574564`) currently cause errors. I'm actually going to leave this one open and close #401 so that other error notifications will point the user to this issue.

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: bug, uncaught-exception
