### ISSUE TITLE
Deleting last word in line deletes whole line.

### ISSUE THREAD

**Issue by Zaba999** [atom/vim-mode#736] opened 2015-07-03 08:41 UTC
This is not standard Vim behavior and is quite annoying.
To reproduce please write one word in line and delete it with dw command.

**Comment by Zaba999** [comment] 2015-07-07 13:56
Additional info is that it's connected with line endings as on file with Windows style line endings it works properly.

**Comment by RedFT** [comment] 2015-08-15 12:09
I can confirm this issue and run into it frequently.

**Comment by georgeaf99** [comment] 2015-11-22 05:01
After investigating for the way *MoveToNextWord* and *Delete* work I think I've found the source of the issue. In Vim *w* moves the cursor to the next line if the word is at the end of a line; however, *dw* keeps the cursor on the end of the line if the last word of a line is deleted. Thus, it seems that the cursor behavior when using *dw* must override that of *w*.

NOTE: not sure if *d* in Vim always overrides this end-of-line behavior or only when chained with *w*

**Comment by hitchcockwill** [comment] 2016-01-07 15:00
Any progress on this issue? This is a particularly annoying bug.

**Comment by RobertMaloney** [comment] 2016-01-09 03:26
:+1:

**Comment by paween1980** [comment] 2016-01-21 11:21
I will be waiting for this bug.

**Comment by tangledhelix** [comment] 2016-06-07 00:31
👍

**Comment by lee-dohm** [comment] 2018-04-05 17:27
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:27 UTC
Labels: bug
