### ISSUE TITLE
Selecting inside brackets works only partially – keymap problem

### ISSUE THREAD

**Issue by flannelhead** [atom/vim-mode#482] opened 2015-01-08 12:51 UTC
I use the "select inside brackets" motions like 'ci[', 'ca{' etc. heavily in Vim, and noticed that most of them don't work in vim-mode. I think I've pretty much nailed it now: it seems that there's a problem with the keybindings to those commands.

The problematic commands those involving shift: for example, the mapping `'i b': 'vim-mode:select-inside-parentheses'` does what is expected, ie. I can use 'cib' to change text inside parentheses, but `'i (': 'vim-mode:select-inside-parentheses'` doesn't (typing the '(' involves pressing shift). Also, `'i \''` works but `'i "'` doesn't. So I think there's a pattern there. Now I think this might rather be a problem with the keybinding resolver and I'm going to investigate it further, but I'm reporting this here anyway so that you know these commands aren't currently working.

FWIW, I'm running Atom v0.168.0 on Arch Linux x86_64. Fresh install, no other plugins. Thanks for your work on this vim-mode already, it seems all the important stuff is implemented and the multiple cursors support is especially awesome!

**Comment by maxbrunsfeld** [comment] 2015-01-08 18:16
I think this is a duplicate of #403. If you discover anything more about the problem, please post it there. Thanks!

**Closed by maxbrunsfeld** 2015-01-08 18:16 UTC
