### ISSUE TITLE
Keys don't work without double-type when in key binding

### ISSUE THREAD

**Issue by dakotahp** [atom/vim-mode#499] opened 2015-01-28 22:19 UTC
_Forgive me if this has already been discussed, I couldn't find any existing issues that exactly described this._

I am one of the people that use the `jk`, `kj`, `jj`, et cetera key bindings to trigger escape mode. In vim, what happens is in input mode if you type of these characters the key is held briefly while it waits for the other character and then is "typed" after that brief delay.

In this package what happens is the key does not work at all unless you hit it twice. This functionality is inconsistent and breaks the flow because any words typed with a key-bound key silently fails instead of the way vim does it which is far more desirable.

**Comment by jeffschwartz** [comment] 2015-01-28 22:21
+1

**Comment by TeardropInc** [comment] 2015-01-29 19:25
I suppose I'd be irresponsible if I didn't add steps to reproduce:

1. Enable the vim package
2. Add the following to the user keymap (`keymap.cson`):
```cson
'.editor.vim-mode:not(.mini)':
  'k j': 'vim-mode:activate-command-mode'
  'j k': 'vim-mode:activate-command-mode'
```
3. Go into a document and hit `i` to get into insert mode if it isn't already.
4. Try to type `just kidding` without being infuriated.

To see how vim does it add the following to your `.vimrc` file:
```vim
inoremap kj <Esc>
```

**Comment by gepoch** [comment] 2015-01-30 02:18
#221 might be interesting to you!

**Comment by TeardropInc** [comment] 2015-01-30 03:26
@gepoch Thanks. I noticed that ticket before but thought the Arpeggio thing made it different but now that I've read it I think they're basically the same issue, the reporter just didn't write his description very well.

**Comment by gepoch** [comment] 2015-01-30 04:39
@TeardropInc yeah. I come from a tradition of emacs, where this functionality is implemented in something called "key-chord-mode"

There are many names for it, because it's a good idea :) It's pretty hard to beat these combos for ease of access. I've learned to live without them because Atom is an awesome platform, but I still miss 'em.

**Comment by tangledhelix** [comment] 2016-08-05 02:37
@dakotahp I use this, which lets me type "just kidding" without any aggravation:

```
'atom-text-editor.vim-mode.insert-mode':
    'j j': 'vim-mode:activate-normal-mode'
    'j k': 'vim-mode:activate-normal-mode'
```

I also added a `kj` mapping to test, and it also had no issues. In the rare weird cases where for some reason I actually want to type a `jj` or `jk` of course, it's annoying, but that's pretty rare.

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: bug
