### ISSUE TITLE
Commands duplicate actions after update

### ISSUE THREAD

**Issue by TeardropInc** [atom/vim-mode#551] opened 2015-03-06 18:14 UTC
I suspect this might be an Atom bug rather than `vim-mode` but I'll start by sharing the issue here:

After I update this package the movement commands double up so the `j` and `k`, for instance, now jump by two lines as opposed to one. This problem goes away after a reboot and this has been going on for at least 4 versions and I think that Atom might not be clearing out the old version after update and instead the events from the old and new package are still bound and firing successively. 

This is just my interpretation because it is an old issue and rebooting completely fixes it so I suspect I should report this to Atom if the project lead of this determines this to be an Atom issue.

**Comment by maxbrunsfeld** [comment] 2015-03-07 00:48
This is a duplicate of #480. It is a vim mode bug; sometimes vim-mode fails to deactivate.

**Closed by maxbrunsfeld** 2015-03-07 00:48 UTC
