### ISSUE TITLE
Cursor position does not move when mouse scrolling in window

### ISSUE THREAD

**Issue by billyvg** [atom/vim-mode#965] opened 2016-02-11 18:59 UTC
If you use your mouse to scroll inside the editor, your cursor position does not update to always be in view.

Reproduce
1) Open a large file and have cursor on the first line
2) Use mouse to scroll to the bottom of the file
3) Press ESC, editor will set focus to cursor position at start of file

I suppose this exposes my bad habits (mouse scrolling and pressing ESC very often).

**Comment by tangledhelix** [comment] 2016-09-30 14:42
I suppose this is a matter of opinion, but I have always viewed this behavior as a feature, not a bug. I often scroll around a file to look at something, but do not want the cursor to move from the current position. Then I can `zz` to get back where I was already working.

Is the behavior you describe the way Vim behaves? Sure - but only because "the cursor is always visible in the viewport" is a limitation inherent in a terminal emulator.

**Comment by lee-dohm** [comment] 2018-04-05 16:45
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:45 UTC
