### ISSUE TITLE
Operators replace text with motion when used with pane splits

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#657] opened 2015-05-08 17:18 UTC
If you split a pane and then delete a line in the original pane using `dd`, the line gets deleted but a `d` is inserted at the beginning of the next line (even after closing the opened pane).

The same thing happens with `cc` to change the line (except it inserting a `c`, not a `d`).

**Comment by jazzpi** [comment] 2015-05-16 15:18
I just noticed this seems to apply to any operator with motions - for example, going to the beginning of the document and then pressing `G` to yank the entire document does that - and replace the document with `G`. This basically makes pane splits unusable.

**Comment by bronson** [comment] 2015-05-21 08:45
That's strange, I can't reproduce this.  I split a pane (both using ex mode's :split and the menu), hit dd, and both panes had the correct text.  Tried a few other motions too.

Does it happen when you only have vim-mode enabled, no other 3rd party plugins?

**Comment by jazzpi** [comment] 2015-05-28 18:18
I think this fixed itself when I upgraded Atom, I'm unable to reproduce this now.

**Comment by romgrk** [comment] 2015-05-30 01:23
Still poping for me, with atom v0.204.0.
Happens only when I'm working with split panes.

**Comment by jazzpi** [comment] 2015-05-30 10:56
Strange, it happens again for me now. I don't know why, but I'm pretty sure it worked for a while - maybe I just worked in the new pane everytime?

**Comment by jazzpi** [comment] 2015-05-30 11:04
Alright, here's something interesting:

* Open a new window
* Enter
```
abc
def
ghi
```
into the `untitled` file
* Press `Ctrl-V`, then `Ctrl-H`
* Go to the first line, press `dd`. File now looks like
```
ddef
ghi
```
* Press `u`, then press `cc`, then `Esc`. File now looks like
```
abc
c
ghi
```
* Press `u`, then delete a line. It now works correctly again.

**Comment by jazzpi** [comment] 2015-06-10 11:56
This happens too when I disable all packages but vim-mode.
If I do this on a clean install with only vim-mode installed, it works however.

**Comment by ssfrr** [comment] 2015-07-08 21:12
I'm seeing this as well, and actually originally attributed it to bronson/vim-mode-next#1. I can reliably trigger it by opening a vertical split, or closing a vertical split if I opened Atom with one. Closing the split again doesn't fix the problem. After I restart Atom the problem goes away though. I tried this with all other plugins disabled. It does seem to be reliably reproducible.

Strangely doing `yy` to yank a line causes the line to disappear (and the letter `y` is prepended to the next line).

Yanking from the command palette does not delete the line though.

**Comment by bronson** [comment] 2015-07-08 21:27
You mean `Ctrl-W v` right?  (lower case, ctrl-w ctrl-v should be the same)

I still can't reproduce this.  :-/

My full typing sequence (spaces are just for readability

    cmd-shift-N i abc <cr> def <cr> ghi <esc> Ctrl-w v Ctrl-w h 1G dd

First line gets deleted in both panes, everything looks good so far (except the 1G left the cursor one position too far to the right, the ol' cursor-outside-the-line bug)

    u cc <esc> u dd

Every edit worked exactly as intended.  What platform are you on?  (me: OSX and sometimes Linux)

**Comment by jazzpi** [comment] 2015-07-18 10:16
Alright, I can't reproduce this on a fresh install (although I could with everything in `init.coffee`, `config.cson` and `keymap.cson` commented out and all packages but Core and `vim-mode` disabled...).

On the fresh install, I however notice a similar issue - the following sequence inserts a `:` into the file :confused:

<kbd>ctrl-w</kbd> <kbd>v</kbd> <kbd>ctrl-w</kbd> <kbd>h</kbd> <kbd>:</kbd>

I can only test on Linux.

**Comment by jazzpi** [comment] 2015-07-18 10:17
Same thing happens when replacing <kbd>:</kbd> with <kbd>q</kbd>

Looks like unbound keys simply insert, even in command mode (when used with pane splits).

**Comment by jazzpi** [comment] 2015-07-18 15:13
And another one: <kbd>c</kbd><kbd>w</kbd> replaces the word with `w`.

**Comment by bronson** [comment] 2015-07-18 17:46
Ha!  I can reproduce the last one.  That's weird!

I fire up Atom with a single editor pane.  Hit `ctrl-w v` to split, then `cw`.  The whole thing gets ignored.  Now `ctrl-w ctrl-w` to switch to the original pane and `cw`.  A 'w' gets inserted into the editor.

That's some suboptimal behavior.

**Comment by bronson** [comment] 2015-07-18 17:48
Except I can't reproduce any of that when vim-surround is disabled and Atom restarted.  Works perfectly now.

Are you using vim-surround?

**Comment by jazzpi** [comment] 2015-07-18 17:52
No, I'm not using vim-surround.

It seems kind of random what sequences trigger this behavior. I'll look into this when I'm done with #762

**Comment by bronson** [comment] 2015-07-18 18:12
I reproduced it a few times, restarting Atom each time...  And now all of a sudden I can't reproduce it at all.  Both with and without vim-surround, I don't see it anymore.  So weird!  Looking forward to #762.

**Comment by jazzpi** [comment] 2015-07-19 20:36
Alright, it looks like in the pane where this bug occurs,

```coffeescript
atom.views.getView(atom.workspace.getActiveEditor()).component.isInputEnabled
```

is `true` in command mode for some reason. (This is `@editorElement.component.isInputEnabled` in the `VimState`)

**Comment by jazzpi** [comment] 2015-07-19 20:53
... And entering and exiting insert mode makes everything work alright. Looks like `isInputEnabled` is set to `true` when splitting panes.

**Comment by lee-dohm** [comment] 2018-04-05 17:32
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:32 UTC
