### ISSUE TITLE
No longer updated?

### ISSUE THREAD

**Issue by v3ss0n** [atom/vim-mode#1045] opened 2016-07-25 13:26 UTC
Is this package is dead? vim-mode-plus is successor ?

**Comment by DrakeXiang** [comment] 2016-09-22 04:19
+1

**Comment by plbowers** [comment] 2016-09-26 19:55
I, too, would like to know if this package is dead...

I've been working hard on a few modifications/enhancements, but if there's low probability of them getting merged into the master trunk (it looks like the last merge happened in March?) then I'm not sure I want to keep working on them...

**Comment by v3ss0n** [comment] 2016-09-26 20:31
total of 39 PRs.. would be a shame if this package is dead  , someone should take over.

**Comment by maxbrunsfeld** [comment] 2016-09-28 16:31
We're not developing new features on this package right now, though we still want to fix regressions and keep it working. A lot of people now use vim-mode-plus which is very well maintained.

**Comment by v3ss0n** [comment] 2016-09-29 00:02
ok then checking out vim-mode-plus

**Comment by plbowers** [comment] 2016-09-29 11:40
If this is the official status of this package then it REALLY needs to be made clear. From a quick read it looked like vim-mode-plus was a breakaway fork and this was still the standard-bearer for vim within atom. Now I've spent a few weeks learning the package and implementing some new features and now I find out that vim-mode-plus is not a "rogue breakaway" but the official new standard-bearer. Please make this clear as it will make a BIG difference to people deciding between the 2 packages...

**Comment by plbowers** [comment] 2016-10-01 14:50
It should also be notated at https://atom.io/packages/vim-mode unless the README automatically gets displayed there...

**Comment by lee-dohm** [comment] 2018-04-05 16:01
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:01 UTC
