### ISSUE TITLE
ci'  command does not work

### ISSUE THREAD

**Issue by mushketyk** [atom/vim-mode#853] opened 2015-08-31 08:22 UTC
**Version:** 0.59.0

**How to reproduce:**
1. Create a new file
2. Write: 'my-project'
3. In normal mode set cursor to character "o"
4. Enter the following command: ci'

**What happens:** nothing
**What should happen:** "my-project" should be removed and editor should enter insert mode

**Comment by jacekkopecky** [comment] 2015-08-31 14:05
@mushketyk can you please check what the Key Binding Resolver (toggled with `cmd-.` or in the Packages menu) shows when you've pressed `ci'`?

**Comment by mushketyk** [comment] 2015-09-05 17:01
@jacekkopecky Hi, I could only find bindings for "c" in Packages -> Settings View -> Show Keybindings:

**Comment by mushketyk** [comment] 2015-09-05 17:02
I also noticed that I can reproduce this bug only from time to time and if I restart Sublime everything works fine again.

**Comment by jacekkopecky** [comment] 2015-09-05 18:26
I'm especially interested in what the keybinding resolver shows when you
press c and ' please.

Also, you are restarting Atom along with Sublime, right? :smiley:

**Comment by alexbooker** [comment] 2015-09-06 14:57
I am a new `vim-mode` user and this is a limitation I have encountered as well.

The _Key Binding Resolver_ shows `i'`.

And here is the code I am trying to perform the operation on:

```elixir
ExUnit.start

defmodule MyTest do
  use ExUnit.Case
    test 'i wanna replace text in here pls' do
      assert 1 + 1 == 2
    end
end
```

**Comment by alexbooker** [comment] 2015-09-12 01:37
Is there any more information you would like from me?

I noticed that `ci{` etc. works fine.

**Comment by jacekkopecky** [comment] 2015-09-12 06:06
@alexbooker can you reliably reproduce the condition? I tried `ci'` in various places of your test name and it worked properly. And if you can reproduce it, does it also show up when you disable packages other than vim-mode and restart Atom?
 
It could also be that the user sometimes, through a distraction, spends more than a second between typing `i` and `'` – that would cancel the Atom command.

**Comment by alexbooker** [comment] 2015-09-12 11:20
> Can you reliably reproduce the condition?

@jacekkopecky Yes, I can.

> And if you can reproduce it, does it also show up when you disable packages other than vim-mode and restart Atom?

Yes.

> It could also be that the user sometimes, through a distraction, spends more than a second between typing i and ' – that would cancel the Atom command.

It *does* work with `ci{` etc. so I do not think this is the problem.

I am running Atom 1.0.11 on Windows 10 64bit. I'll try reinstalling Atom now. 

Any other questions I can answer to help solve this? Thanks.

**Comment by 50Wliu** [comment] 2015-09-12 15:10
@alexbooker can you also please paste the output of `apm list --installed` here (and/or try to disable all community packages except vim-mode)?  Thanks.

**Comment by alexbooker** [comment] 2015-09-12 15:47
*Eureka!*

This issue stems from using *English (United Kingdom)* keyboard layout. It works if I use *English (United States)*.

Makes sense because @mushketyk and I are both in the United Kingdom.

**How to reproduce:** 

(On Windows 10) 

1. Change keyboard layout to *English (United Kingdom)* ([*tutorial*](https://acer.custhelp.com/app/answers/detail/a_id/37408/~/windows-10%3A-changing-keyboard-layout)).
2. Follow steps in OP

**Other:**

I dunno if this is a problem with *vim-mode* or *Atom* in general because [*vim-surround*](https://github.com/gepoch/vim-surround) commands that involve `'` or `"` do not work with *English (United Kingdom)* either... //cc @gepoch

**Comment by 50Wliu** [comment] 2015-09-12 17:49
Do you need to press AltGr to get to '?

**Comment by alexbooker** [comment] 2015-09-12 17:50
What do you mean *"get to `"*?

**Comment by alexbooker** [comment] 2015-09-12 19:01
@50Wliu No I do not - I _never_ use AltGr.

**Comment by alexbooker** [comment] 2015-09-14 10:57
Is there any more information I can provide? I *really* miss this feature :cry:

**Comment by jacekkopecky** [comment] 2015-09-14 11:13
@alexbooker in case you haven't already, can you please try it with https://atom.io/packages/keyboard-localization installed? Cf #709
I don't have Windows so I can't reproduce it.

**Comment by alexbooker** [comment] 2015-09-14 11:40
@jacekkopecky That definitely helped - now I can use `ci"` but `ci'` still does not work.

**Comment by alexbooker** [comment] 2015-09-14 13:39
Upon further inspection [*keyboard-localization*](https://atom.io/packages/keyboard-localization) works very well for me and it *should* for @mushketyk, too.

I generated a custom keymap using [these instructions](https://github.com/andischerer/atom-keyboard-localization#generate-your-own-keymap):

```json
{
    "50": {
        "shifted": 34
    },
    "192": {
        "unshifted": 39
    }
}
```

And now `ci"` and `ci'` work fine. [*vim-surround*](https://github.com/gepoch/vim-surround) commands involving `'` and `"` work fine now as well.

**Comment by lee-dohm** [comment] 2018-04-05 16:59
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:59 UTC
Labels: more-information-needed, needs-reproduction
