### ISSUE TITLE
Key 'k' to go up after visual selection using 'v' doesn't work in lines with soft wrap.

### ISSUE THREAD

**Issue by sarojkh** [atom/vim-mode#956] opened 2016-01-28 08:05 UTC
When going up the lines using 'k'  during visual selection using 'v', the navigation(going up) stops at line with soft wrap.  However, going down with key 'j'  in the same scenario works as anticipated.

I have both 'Soft Wrap' & 'Soft Wrap At Preferred Line Length' checked in the settings. 

Occured in :
*.txt file 
vim-mode 0.64.0
ex-mode 0.8.0
Atom 1.4.1
OS X 10.11.3

**Comment by schmolly159** [comment] 2016-03-01 18:07
I have this issue and it is not just the 'k' key, but it depends on which direction you first moved for the visual selection.  It also only occurs for me on full-line visual (Shift+v).  Normal visual mode (v) can return past the soft wrap.

Steps to reproduce:

1. Open a file with soft wrapping
2. Enter full-line visual mode (Shift+v)
3. Move cursor past the soft wrap, highlighting the soft wrapped line
4. Attempt to back up toward the initial highlight position and you cannot go back past the soft wrapped line.

**Comment by lee-dohm** [comment] 2018-04-05 16:45
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:45 UTC
