### ISSUE TITLE
Uncaught TypeError: this.editorElement.getScrollTop is not a function

### ISSUE THREAD

**Issue by klorenz** [atom/vim-mode#909] opened 2015-11-04 21:49 UTC
[Enter steps to reproduce below:]
1. ... Type ctrl-b for going page up

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0
### Stack Trace

Uncaught TypeError: this.editorElement.getScrollTop is not a function

```
At /home/kiwi/.atom/packages/vim-mode/lib/motions/general-motions.coffee:478

TypeError: this.editorElement.getScrollTop is not a function
  at ScrollFullUpKeepCursor.ScrollKeepingCursor.scrollScreen (/home/kiwi/.atom/packages/vim-mode/lib/motions/general-motions.coffee:478:93)
  at ScrollFullUpKeepCursor.ScrollKeepingCursor.execute (/home/kiwi/.atom/packages/vim-mode/lib/motions/general-motions.coffee:467:18)
  at VimState.module.exports.VimState.processOpStack (/home/kiwi/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
  at VimState.module.exports.VimState.pushOperations (/home/kiwi/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
  at atom-text-editor.commands.(anonymous function) (/home/kiwi/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/kiwi/github/atom/src/command-registry.coffee:245:27)
  at /home/kiwi/github/atom/src/command-registry.coffee:1:1
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/home/kiwi/github/atom/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/kiwi/github/atom/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/home/kiwi/github/atom/src/window-event-handler.coffee:76:18)

```
### Commands

```
     -0:37.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 32x -0:35.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:33.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 25x -0:32.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 39x -0:31.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 19x -0:29.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 15x -0:27.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 38x -0:26.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:24.6.0 vim-mode:scroll-full-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:23.7.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:21.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:20.9.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:20.1.0 vim-mode:scroll-full-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:11.1.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 10x -0:09.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.7.0 vim-mode:scroll-full-screen-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "twilight"
    ],
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "*.pyc"
    ],
    "disabledPackages": [
      "pigments"
    ],
    "audioBeep": false
  },
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
aligner, v0.17.1
atom-xikij, v0.9.4
autocomplete-clang, v0.8.8
autocomplete-paths, v1.0.2
build, v0.47.0
build-make, v0.2.1
character-table, v0.4.3
color-picker, v2.0.13
email, v0.5.1
ex-mode, v0.7.0
file-icons, v1.5.1
git-log, v0.4.1
hidpi, v0.7.0
imdone-atom, v1.1.53
isotope-ui, v2.7.0
language-apache, v1.3.0
language-cmake, v0.1.4
language-pegjs, v0.5.0
language-php, v0.32.0
language-restructuredtext, v0.9.0
navigate-indent, v0.1.0
project-manager, v2.6.5
python-tools, v0.6.5
regex-railroad-diagram, v0.10.4
tidy-tabs, v0.3.0
twilight, v0.3.0
vim-mode, v0.63.0
web-browser, v1.5.0
widget-toolkit, v0.0.1

# Dev
atom-xikij, v0.9.4
build, v0.47.0
build-make, v0.2.1
build-npm-apm, v0.2.0
character-table, v0.4.3
email, v0.5.1
language-php, v0.32.0
navigate-indent, v0.1.0
regex-railroad-diagram, v0.10.4
```

**Comment by maxbrunsfeld** [comment] 2015-11-04 21:54
I'm not sure what could cause this. Does it happen if you disable all your packages except for vim-mode `mv ~/.atom/packages ~/.atom/packages.bak && apm install vim-mode`?

**Comment by tuvistavie** [comment] 2015-11-06 02:42
Hi,

I have the same issue here, it happens when I try to yank (`yy` or any other yank command gives the same issue).
The issue occurs only with vim-mode 0.63.0 and when other packages are installed.
I am not sure which package is causing the issue though.
Reverting to 0.62.0 fixes the issue. Disabling all packages except for vim-mode also does.

Here is what atom gives me.


**Atom Version**: 1.0.19
**System**: "Arch Linux"
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0

### Stack Trace

Uncaught TypeError: this.editorElement.getScrollTop is not a function

```
At /home/daniel/.atom/packages/vim-mode/lib/vim-state.coffee:276

TypeError: this.editorElement.getScrollTop is not a function
  at Yank.execute (/home/daniel/.atom/packages/vim-mode/lib/operators/general-operators.coffee:182:29)
  at VimState.module.exports.VimState.processOpStack (/home/daniel/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
  at VimState.module.exports.VimState.processOpStack (/home/daniel/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
  at VimState.module.exports.VimState.pushOperations (/home/daniel/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
  at atom-text-editor.commands.(anonymous function) (/home/daniel/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  2x -0:01.2.0 vim-mode:yank (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "packagesWithKeymapsDisabled": [
      "rspec",
      "terminal-plus",
      "ruby-block",
      "rails-rspec"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-alignment, v0.12.1
atom-jade, v0.3.0
atom-ternjs, v0.8.4
autocomplete-elixir, v1.4.2
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.14
haskell-ghc-mod, v1.1.1
jshint, v1.8.3
keyboard-localization, v1.4.10
language-elixir, v0.5.2
language-fish-shell, v1.0.2
language-haskell, v1.4.12
linter, v1.10.0
linter-elixirc, v1.1.0
linter-hlint, v0.4.2
linter-jscs, v3.2.0
linter-rubocop, v0.4.4
minimap, v4.16.0
pretty-json, v0.4.1
rspec-snippets, v0.4.0
ruby-block, v0.3.5
terminal-plus, v0.13.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by iofjuupasli** [comment] 2015-11-13 10:42
[Enter steps to reproduce below:]

1. yank (any, always)

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0


### Stack Trace

Uncaught TypeError: this.editorElement.getScrollTop is not a function

```
At /home/iofjuupasli/.atom/packages/vim-mode/lib/vim-state.coffee:276

TypeError: this.editorElement.getScrollTop is not a function
  at Yank.execute (/home/iofjuupasli/.atom/packages/vim-mode/lib/operators/general-operators.coffee:182:29)
  at VimState.module.exports.VimState.processOpStack (/home/iofjuupasli/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
  at VimState.module.exports.VimState.processOpStack (/home/iofjuupasli/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
  at VimState.module.exports.VimState.pushOperations (/home/iofjuupasli/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
  at atom-text-editor.commands.(anonymous function) (/home/iofjuupasli/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:10.8.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  5x -0:10.6.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.7.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -0:09.6.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:08.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:08.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:08.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.6.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.6.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:07.2.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:03.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.8.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.8.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.7.0 vim-mode:yank (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "deprecation-cop",
      "styleguide",
      "wakatime",
      "archive-view",
      "background-tips",
      "dev-live-reload",
      "feedback",
      "incompatible-packages",
      "keybinding-resolver",
      "welcome",
      "open-on-github",
      "release-notes",
      "atom-pair",
      "smalls"
    ],
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-beautify, v0.28.17
atom-ternjs, v0.8.4
color-picker, v2.0.13
editorconfig, v1.2.2
emmet, v2.3.14
file-icons, v1.6.11
highlight-selected, v0.10.1
language-docker, v1.1.3
linter, v1.11.0
linter-eslint, v4.0.0
linter-jscs, v3.2.0
linter-jshint, v1.2.1
live-archive, v0.1.15
smart-tab-name, v1.0.4
tab-numbers, v0.3.0
tasks, v2.5.1
vim-mode, v0.63.0
vim-surround, v0.8.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by iofjuupasli** [comment] 2015-11-13 10:57
I can't reproduce it after update to atom 1.2.0 !

**Comment by lee-dohm** [comment] 2018-04-05 16:58
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:58 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception
