### ISSUE TITLE
Implement 'R' for replace mode

### ISSUE THREAD

**Issue by fazlearefin** [atom/vim-mode#700] opened 2015-06-11 12:26 UTC
Pressing `R` in command mode will place the editor in replace mode for overwriting existing characters.

**Comment by jacekkopecky** [comment] 2015-06-11 12:29
There's a PR #573 for this, but it got no comment from the maintainers.

**Comment by fazlearefin** [comment] 2015-06-11 12:34
Great! Hope the maintainers notice this and does something about your PR #573

**Comment by gittyupagain** [comment] 2015-06-11 19:54
+1

**Comment by bronson** [comment] 2015-06-26 05:57
This is a dupe of #562.  And I really do wish #573 would be merged or commented on.

**Comment by lurimendes** [comment] 2015-07-01 22:12
+1

**Comment by tangledhelix** [comment] 2016-10-27 03:15
Replace mode was merged some time ago - this issue can be closed, I think.

**Closed** 2016-10-27 03:20 UTC
