### ISSUE TITLE
Input VIT, complex HTML, the choice is not correct

### ISSUE THREAD

**Issue by doneself** [atom/vim-mode#858] opened 2015-09-08 14:40 UTC
Input VIT, complex HTML, the choice is not correct

**Comment by MarkusSN** [comment] 2015-09-17 20:37
Duplicate of #835?

**Comment by lee-dohm** [comment] 2018-04-05 16:58
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:58 UTC
