### ISSUE TITLE
ctrl-v virtual mode can not enable column edit.

### ISSUE THREAD

**Issue by summer1988** [atom/vim-mode#516] opened 2015-02-11 02:09 UTC
In some previous version. ctrl-v can enable virtual mode with column edit.
Now it can't but enable a block select.  Am I something wrong?

**Comment by nosami** [comment] 2015-05-07 20:28
Just came here to report the same issue. Visual block mode doesn't work with ctrl-v

**Comment by bronson** [comment] 2015-05-21 08:05
This is a dupe of #468

**Comment by LukeSwart** [comment] 2015-07-25 10:10
`Visual block mode doesn't work with ctrl-v`
Same here.

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
