### ISSUE TITLE
Blockwise-visual-mode not working

### ISSUE THREAD

**Issue by TheLuckyOne** [atom/vim-mode#645] opened 2015-04-30 15:36 UTC
Hi! 
Vim-mode:activate-blockwise-visual-mode not working on my mac, linux and windows. 
What am i doing wrong?

**Comment by bronson** [comment] 2015-05-21 06:45
Get this, Atom doesn't support block select yet: https://github.com/atom/atom/issues/2306

Apparently there's been some work but nothing usable yet.  If Atom 1.0 ships without block select, that would be downright embarrassing.

**Comment by bronson** [comment] 2015-05-21 08:02
Also, this is a dupe of https://github.com/atom/vim-mode/issues/516

**Closed** 2015-10-30 07:47 UTC
