### ISSUE TITLE
Insert text repeatedly

### ISSUE THREAD

**Issue by dmfilipenko** [atom/vim-mode#859] opened 2015-09-08 15:41 UTC
Command `3i` don't repeat entered text 3 times.

**Comment by jacekkopecky** [comment] 2015-09-08 16:28
Duplicate of #580, addressed in #609 which is waiting on the resolution of #568 v #849.

**Comment by 50Wliu** [comment] 2015-09-09 01:16
Thanks @jacekkopecky.

**Closed by 50Wliu** 2015-09-09 01:16 UTC
