### ISSUE TITLE
win8.1 Ctrl+V block choose not like the vim

### ISSUE THREAD

**Issue by zwfy1** [atom/vim-mode#923] opened 2015-11-15 12:38 UTC
In the vim, I can choose one or multi-rows use CTRL+V,but in vim-mode,CTRL+V only choose multi-lines, I like this plugin, wish this bug could be fixed! Thank you !

**Comment by denqxotl** [comment] 2015-12-13 22:45
Same trouble. Mac OS

**Comment by shadowwalkersb** [comment] 2015-12-14 15:25
Confirmed on Mac, Windows and Linux.

**Comment by jamesgecko** [comment] 2016-05-20 15:12
Duplicate of #468.

**Comment by 50Wliu** [comment] 2016-05-23 16:17
Thanks @jamesgecko.

**Closed by 50Wliu** 2016-05-23 16:17 UTC
Labels: duplicate
