### ISSUE TITLE
Uncaught TypeError: this.editor.buffer.getChangesSinceCheckpoint is not a function

### ISSUE THREAD

**Issue by shitou520** [atom/vim-mode#1042] opened 2016-07-14 02:59 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0-beta2
**System**: Mac OS X 10.11.5
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1
### Stack Trace

Uncaught TypeError: this.editor.buffer.getChangesSinceCheckpoint is not a function

```
At /Users/caochao/.atom/packages/vim-mode/lib/vim-state.coffee:456

TypeError: this.editor.buffer.getChangesSinceCheckpoint is not a function
    at VimState.module.exports.VimState.deactivateInsertMode (/Users/caochao/.atom/packages/vim-mode/lib/vim-state.coffee:456:30)
    at VimState.module.exports.VimState.activateNormalMode (/Users/caochao/.atom/packages/vim-mode/lib/vim-state.coffee:392:6)
    at atom-text-editor.registerCommands.activate-normal-mode (/Users/caochao/.atom/packages/vim-mode/lib/vim-state.coffee:66:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -7:41.4.0 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -7:40.8.0 core:backspace (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  3x -7:40 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -7:16.5.0 core:save (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -6:41 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  3x -6:05.4.0 core:save (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -3:12.5.0 editor:newline (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -3:01.4.0 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  3x -2:57.8.0 core:backspace (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  7x -0:41.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -0:22.9.0 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -0:22.6.0 core:move-left (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  5x -0:22 core:move-right (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  7x -0:20.3.0 core:backspace (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -0:07.8.0 core:save (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
  2x -0:01.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "batman-syntax"
    ]
  },
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
autocomplete-go, v1.1.0
batman-syntax, v1.0.1
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.14
navigator-godef, v1.0.3
nucleus-dark-ui, v0.9.0
pdf-view, v0.50.0
tester-go, v1.0.4
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by atd** [comment] 2016-07-22 14:02
Upgrading to atom 1.8.0 solves the issue, but raises https://github.com/atom/status-bar/issues/143

**Comment by 50Wliu** [comment] 2016-07-22 14:35
@atd please follow the instructions at the bottom of that issue.

@shitou520 Can you still reproduce this on Atom 1.8.0?

**Comment by atd** [comment] 2016-07-22 14:44
Thank you @50Wliu I already did.  Last issue disappears after reinstalling

**Comment by lee-dohm** [comment] 2018-04-05 16:03
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:03 UTC
Labels: more-information-needed, uncaught-exception
