### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

### ISSUE THREAD

**Issue by Arsca** [atom/vim-mode#701] opened 2015-06-11 15:54 UTC
[Enter steps to reproduce below:]
1. Activate the vim search mode "/"
2. Enter the search string
3. Press enter

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.51.0
### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:207

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:207:51)
  at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:182:26)
  at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:612:27)
  at vim-command-mode-input.VimCommandModeInputElement.removePanel (/Users/arsca/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:57:36)
  at vim-command-mode-input.VimCommandModeInputElement.confirm (/Users/arsca/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:47:6)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:19.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -0:16.6.0 core:move-down (input.hidden-input)
     -0:15.8.0 core:confirm (input.hidden-input)
     -0:12 core:backspace (input.hidden-input)
     -0:11.3.0 vim-mode:activate-command-mode (input.hidden-input)
     -0:10.5.0 vim-mode:search (input.hidden-input)
     -0:06.3.0 core:confirm (input.hidden-input)
  3x -0:06.3.0 blur (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-bold-syntax"
    ],
    "projectHome": "/Users/arsca/Development",
    "disabledPackages": [
      "tualo-git-context",
      "terminal-status",
      "git-difftool",
      "atomatigit",
      "linter-jscs",
      "atom-minjs",
      "symbols-view"
    ]
  },
  "vim-mode": {
    "startInInsertMode": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.1.2
atom-handlebars, v0.5.0
atom-jasmine, v0.5.0
atom-runner, v2.4.1
atom-solarized-dark-ui, v0.25.0
autoclose-html, v0.17.1
autocomplete-modules, v0.3.5
autocomplete-polymer, v0.2.3
color-picker, v2.0.4
docblockr, v0.7.2
ember-cli-helper, v0.7.2
ember-snippets, v1.2.1
emmet, v2.3.10
file-icons, v1.5.7
fonts, v0.4.2
git-blame, v0.4.4
git-control, v0.3.0
git-log, v0.4.1
git-projects, v1.14.1
git-tab-status, v1.9.2
javascript-snippets, v1.0.0
js-patterns-atom-snippets, v0.2.1
jsformat, v0.9.0
json-colorer, v0.3.0
language-ejs, v0.1.0
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-gitignore, v0.2.0
last-cursor-position, v0.9.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
local-history, v3.2.2
markdown-format, v2.5.1
minimap, v4.10.0
minimap-git-diff, v4.1.3
node-debugger, v1.0.5
pretty-json, v0.3.3
project-manager, v1.15.10
remote-edit, v1.8.2
remote-sync, v3.1.2
solarized-dark-bold-syntax, v0.2.0
ssh-config, v0.10.1
tabs-to-spaces, v0.11.0
tasks, v2.0.2
tree-view-open-files, v0.2.4
vim-mode, v0.51.0
vim-surround, v0.6.1

# Dev
No dev packages
```

**Comment by mrandre** [comment] 2015-06-26 14:41
I also get this error if I use r. eg r <some-character>. Happens every time I do it.

**Comment by sinkingshriek** [comment] 2015-07-09 03:09
I'm also affected by this when I do `f (some-character)` . 
vim-mode: 0.55.0
Atom: 1.0
OS: Ubuntu

**Comment by mrandre** [comment] 2015-07-15 19:35
I also get this error if I use the 't' operator, like ```ct;``` (change 'til semicolon).

**Comment by jacekkopecky** [comment] 2015-07-15 20:43
Atom 1.0.2, vim-mode 0.55.0, I can't reproduce any of this. The original report by @Arsca lists many user packages - any chance any of you could try if any of your user packages might be causing this? In other words, try disabling them all except vim-mode and let's see if the error still occurs. And can you please post the stack trace and the exact atom and vim-mode version info, if the error does indeed still occur?

**Comment by sinkingshriek** [comment] 2015-07-23 00:25
@jacekkopecky, I gave it a shot with all the installed packages disabled except `vim-mode`. Following is the error that I get. 


### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /usr/share/atom/resources/app.asar/src/text-editor-element.js:218

TypeError: Cannot read property 'hiddenInputComponent' of null
    at atom-text-editor.TextEditorElement.blurred (/usr/share/atom/resources/app.asar/src/text-editor-element.js:218:51)
    at HTMLInputElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-element.js:193:26)
    at atom-pane.PaneElement.activated (/usr/share/atom/resources/app.asar/src/pane-element.js:125:19)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:627:27)
    at vim-normal-mode-input.VimNormalModeInputElement.removePanel (/home/shrestyo/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:81:38)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (/home/shrestyo/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:68:19)
    at /home/shrestyo/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:53:28
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
```

### Commands

```
     -0:00.9.0 vim-mode:find (input.hidden-input)
  3x -0:00.8.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-panel",
      "emmet",
      "open-in-browser",
      "linter-jsxhint",
      "block-comment",
      "color-picker",
      "editorconfig",
      "git-tab-status",
      "highlight-line",
      "language-groovy",
      "language-javascript-jsx",
      "linter",
      "sync-settings",
      "save-session",
      "restore-windows",
      "pane-manager",
      "minimap",
      "linter-jscs",
      "linter-eslint"
    ],
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "ignoredNames": [
      "*.class",
      "*.*.bak"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
vim-mode, v0.57.0

# Dev
No dev packages
```

This is in Atom 1.0.2. Ubuntu 14.04. What's funny is that it doesn't happen in my personal computer with Ubuntu 15.04. I'll try comparing the plugins installed in my work and personal computer when I get a chance.

**Comment by jacekkopecky** [comment] 2015-07-23 20:39
hmmm, and just to make sure - you have restarted Atom recently, right? I'll look at this at some point - it's hard because I can't reproduce it myself.

**Comment by sinkingshriek** [comment] 2015-07-25 01:47
Oh. I completely forgot to follow up on this one. @jacekkopecky, yes. Even with the restart it still throws the same error on my work computer which has Ubuntu 14.04 LTS. I'll try upgrading to Ubuntu 15.04 in my work computer and see if that fixes (long shot) because it's working in my personal computer with Ubuntu 15.04.

**Comment by sinkingshriek** [comment] 2015-07-31 21:03
I had to wait to upgrade to 15.04 because I didn't wanted to disrupt my workspace but I recently did upgraded to latest one and the problem still exists. I'm going to completely uninstall Atom and try it one more time.

**Comment by Arsca** [comment] 2015-09-17 01:09
Follow up: I made a fresh installation of the Atom and with fewer packages (most essential for my job). It works ok now. I though I couldn't identify which package might have caused the problem.
Kind regards,

**Comment by RossBarnie** [comment] 2015-09-17 13:15
I can consistently recreate this error on OS X Yosemite. Tried disabling all other user packages, did not fix. Also tried different Syntax and UI themes with no difference.

**Comment by Arsca** [comment] 2015-09-17 22:43
@RossBarnie I'm on OSX Yosemite. I backed up the ~/.atom elsewhere and installed again whole atom. The first package I installed was the node-vim after which I just installed the packages I need one by one.  After every package installed I checked that it won't generate the node-vim error. So far it works ok.

**Comment by RossBarnie** [comment] 2015-09-17 23:21
How did you install atom? I'm wondering if it has anything to do with the
fact to installed mine via homebrew cask.

**Comment by estrattonbailey** [comment] 2015-09-21 21:01
+1 for `r (some-character)`

atom 1.0.11
vim-mode 0.60.0
OS X Yosemite 10.10.5

**Comment by LeezQ** [comment] 2015-09-26 06:17
+1 OS X Yosemite

**Comment by ourway** [comment] 2015-11-02 03:06
+1 OSX El-Capitan, Atom 1.1.0

**Comment by nomatteus** [comment] 2015-11-14 22:37
I kept getting this error when using `r` (replace). I temporarily got rid of my `.atom` settings, and was able to reproduce the issue with the default settings. The fix was to enable the "Use Shadow DOM" setting.

Steps to reproduce:
1. Rename `~/.atom` directory to something like `~/.atom-bak`
2. Open Atom, install `vim-mode` package.
3. Edit a document, and notice that using `r e` replaces a character with no error.
4. Uncheck: Settings > Use Shadow Dom
5. Edit a document, and notice that using `r e` triggers an error.

Bringing back my old settings and checking option "Use Shadow DOM" seems to have fixed this. (Not sure why it was unchecked in the first place.)

**Comment by jasonszhao** [comment] 2015-11-19 05:37
I can confirm that @nomatteus 's workaround works. I didn't have to reset Atom; all I did was enable "Use Shadow DOM."

**Comment by Arsca** [comment] 2015-11-19 13:00
+1

**Comment by motjuste** [comment] 2015-12-24 23:49
+1

**Comment by agektmr** [comment] 2015-12-26 02:36
I have exact same issue re: `r` and `/`. Turning on Shadow DOM seems to have fixed it for now.

**Comment by lee-dohm** [comment] 2018-04-05 17:27
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:27 UTC
Labels: bug, uncaught-exception
