### ISSUE TITLE
vim-mode and italian keyboard

### ISSUE THREAD

**Issue by NPolikurov** [atom/vim-mode#1046] opened 2016-07-25 13:44 UTC
It seems to me that vim-mode is not switching accordingly with the system language switch. For example indenting a line with ">" works only with the physical key of the us layout. When I press the ">" with an us layout activated it works as expected, but when I switch layout to the Italian, and the ">" now is elsewhere, the indentation works only with the previous key where is us ">" lays.

**Comment by 50Wliu** [comment] 2016-07-25 14:12
This is a duplicate of atom/atom-keymap#35 and atom/atom-keymap#37 - feel free to subscribe there for updates and to check out the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.

**Closed by 50Wliu** 2016-07-25 14:12 UTC
