### ISSUE TITLE
Not able to Uninstall Vim-Mode

### ISSUE THREAD

**Issue by zenmeso** [atom/vim-mode#1013] opened 2016-04-25 07:37 UTC
![Image of vim-mode issue](https://s3.amazonaws.com/f.cl.ly/items/3P3Z2E3G1N2k3a400y46/Screen%20Shot%202016-04-25%20at%2012.28.55%20AM.png)
![Image of Atom Vim Issue](https://s3.amazonaws.com/f.cl.ly/items/0b302U0L2h34220K3z1S/Screen%20Shot%202016-04-25%20at%2012.22.39%20AM.png)

**Comment by 50Wliu** [comment] 2016-04-25 16:29
This is a duplicate of atom/atom#11464 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-25 16:29 UTC
