### ISSUE TITLE
Visual Block mode incorrect

### ISSUE THREAD

**Issue by pococito** [atom/vim-mode#953] opened 2016-01-23 17:11 UTC
![image](https://cloud.githubusercontent.com/assets/16767388/12531469/bb3167e8-c1fb-11e5-8812-dc9ec7bccbe0.png)

Out of the three above standard VIM modes, the 

* characterwise mode, marked as `Visual` in vim status line, started with `v` - works correctly
* linewise mode, marked as `Visual Line` vim status line, triggered with 'SHIFT-v` works correctly
* blockwise mode, marked as `Visual Block`, triggered with `CTRL-v` works exactly like characterwise mode, i.e. incorrectly. It should select a block, not a sequence of characters

![image](https://cloud.githubusercontent.com/assets/16767388/12531466/a0c619bc-c1fb-11e5-8984-a03348a6f341.png)

**Comment by rkmarks** [comment] 2016-01-24 02:05
looks like this is a duplicate of #468

**Comment by 50Wliu** [comment] 2016-01-24 03:05
Thanks @rkmarks.

**Closed by 50Wliu** 2016-01-24 03:05 UTC
