### ISSUE TITLE
Support for Programmer Dvorak keyboard layout

### ISSUE THREAD

**Issue by igorhub** [atom/vim-mode#929] opened 2015-12-01 23:18 UTC
Hi! I'm trying out Atom on my Ubuntu 14.04 machine and I found that
most keys for digits and special symbols work in inconsistent,
unpredictable, unvim ways.

This only happens in normal mode, insert mode works perfectly.

**Comment by Tyleo** [comment] 2016-01-26 16:33
+1

**Comment by Tyleo** [comment] 2016-01-26 18:33
I am working around this with the following in my keymap.json for now:
```
# Support for Programmer Dvorak (Template)

# # Key: $
# # Atom: `
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '`': 'vim-mode:move-to-last-character-of-line'
#
# # Key: ~
# # Atom: ~
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   'g ~': 'vim-mode:toggle-case'
#   '~': 'vim-mode:toggle-case-now'
#
# # Key: &
# # Atom: [
#
# # Key: %
# # Atom: {
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '{': 'vim-mode:bracket-matching-motion'
#
# # 'atom-text-editor.vim-mode.normal-mode':
# #   '" {': 'vim-mode:register-prefix'
#
# # 'atom-text-editor.vim-mode.visual-mode':
# #   '" {': 'vim-mode:register-prefix'
#
# # Key: [
# # Atom: 7
# 'atom-text-editor.vim-mode':
#   'ctrl-7': 'vim-mode:reset-normal-mode'
#
# 'atom-text-editor.vim-mode:not(.normal-mode)':
#   'ctrl-7': 'vim-mode:activate-normal-mode'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 7': 'vim-mode:select-inside-square-brackets'
#   'a 7': 'vim-mode:select-around-square-brackets'
#
# # Key: 7
# # Atom: &
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '&': 'vim-mode:repeat-prefix'
#
# # Key: {
# # Atom: 5
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '5': 'vim-mode:move-to-previous-paragraph'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 5': 'vim-mode:select-inside-curly-brackets'
#   'a 5': 'vim-mode:select-around-curly-brackets'
#
# # Key: 5
# # Atom: %
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '%': 'vim-mode:repeat-prefix'
#
# # Key: }
# # Atom: 3
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '3': 'vim-mode:move-to-next-paragraph'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 3': 'vim-mode:select-inside-curly-brackets'
#   'a 3': 'vim-mode:select-around-curly-brackets'
#
# # Key: 3
# # Atom: #
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '#': 'vim-mode:repeat-prefix'
#
# # Key: (
# # Atom: 1
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '1': 'vim-mode:move-to-previous-sentence'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 1': 'vim-mode:select-inside-parentheses'
#   'a 1': 'vim-mode:select-around-parentheses'
#
# # Key: 1
# # Atom: !
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '!': 'vim-mode:repeat-prefix'
#
# # Key: =
# # Atom: 9
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '9': 'vim-mode:auto-indent'
#
# # Key: 9
# # Atom: (
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '(': 'vim-mode:repeat-prefix'
#
# # Key: *
# # Atom: 0
# # 'atom-text-editor.vim-mode.insert-mode':
# #   'ctrl-r 0': 'vim-mode:insert-mode-put'
#
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '0': 'vim-mode:search-current-word'
#
# # 'atom-text-editor.vim-mode.normal-mode':
# #   '" 0': 'vim-mode:register-prefix'
#
# # 'atom-text-editor.vim-mode.visual-mode':
# #   '" 0': 'vim-mode:register-prefix'
#
# # Key: 0
# # Atom: )
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   ')': 'vim-mode:repeat-prefix'
#
# # Key: )
# # Atom: 2
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '2': 'vim-mode:move-to-next-sentence'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 2': 'vim-mode:select-inside-parentheses'
#   'a 2': 'vim-mode:select-around-parentheses'
#
# # Key: 2
# # Atom: @
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '@': 'vim-mode:repeat-prefix'
#
# # Key: +
# # Atom: 4
# # 'atom-text-editor.vim-mode.insert-mode':
# #   'ctrl-r 4': 'vim-mode:insert-mode-put'
#
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   '4': 'vim-mode:move-to-first-character-of-line-down'
#
# # 'atom-text-editor.vim-mode.normal-mode':
# #   '" 4': 'vim-mode:register-prefix'
#
# # 'atom-text-editor.vim-mode.visual-mode':
# #   '" 4': 'vim-mode:register-prefix'
#
# # Key: 4
# # Atom: $
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '$': 'vim-mode:repeat-prefix'
#
# # Key: ]
# # Atom: 6
# 'atom-text-editor.vim-mode.normal-mode':
#   'ctrl-6': 'symbols-view:go-to-declaration'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i 6': 'vim-mode:select-inside-square-brackets'
#   'a 6': 'vim-mode:select-around-square-brackets'
#
# # Key: 6
# # Atom: ^
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '^': 'vim-mode:repeat-prefix'
#
# # Key: !
# # Atom: 8
#
# # Key: 8
# # Atom: *
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '*': 'vim-mode:repeat-prefix'
#
# # Key: #
# # Atom: ß
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   'ß': 'vim-mode:reverse-search-current-word'
#
# # Key: `
# # Atom: ß
# 'atom-text-editor.vim-mode:not(.insert-mode)':
#   'ß': 'vim-mode:move-to-mark-literal'
#
# 'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
#   'i ß': 'vim-mode:select-inside-back-ticks'
#   'a ß': 'vim-mode:select-around-back-ticks'
#
# # Key: @
# # Atom: ]
#
# # Key: ^
# # Atom: }
# # 'atom-text-editor.vim-mode:not(.insert-mode)':
# #   '}': 'vim-mode:move-to-first-character-of-line'

# Support for Programmer Dvorak (Actual)
'atom-text-editor.vim-mode':
  'ctrl-7': 'vim-mode:reset-normal-mode'

'atom-text-editor.vim-mode:not(.normal-mode)':
  'ctrl-7': 'vim-mode:activate-normal-mode'

'atom-text-editor.vim-mode:not(.insert-mode)':
  '`': 'vim-mode:move-to-last-character-of-line'
  'g ~': 'vim-mode:toggle-case'
  '~': 'vim-mode:toggle-case-now'
  '{': 'vim-mode:bracket-matching-motion'
  '5': 'vim-mode:move-to-previous-paragraph'
  '3': 'vim-mode:move-to-next-paragraph'
  '1': 'vim-mode:move-to-previous-sentence'
  '9': 'vim-mode:auto-indent'
  '0': 'vim-mode:search-current-word'
  '2': 'vim-mode:move-to-next-sentence'
  '4': 'vim-mode:move-to-first-character-of-line-down'
  'ß': 'vim-mode:move-to-mark-literal'

'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
  'i 7': 'vim-mode:select-inside-square-brackets'
  'a 7': 'vim-mode:select-around-square-brackets'
  'i 5': 'vim-mode:select-inside-curly-brackets'
  'a 5': 'vim-mode:select-around-curly-brackets'
  'i 3': 'vim-mode:select-inside-curly-brackets'
  'a 3': 'vim-mode:select-around-curly-brackets'
  'i 1': 'vim-mode:select-inside-parentheses'
  'a 1': 'vim-mode:select-around-parentheses'
  'i 2': 'vim-mode:select-inside-parentheses'
  'a 2': 'vim-mode:select-around-parentheses'
  'i 6': 'vim-mode:select-inside-square-brackets'
  'a 6': 'vim-mode:select-around-square-brackets'
  'i ß': 'vim-mode:select-inside-back-ticks'
  'a ß': 'vim-mode:select-around-back-ticks'
```

**Comment by bengotow** [comment] 2016-01-27 08:38
I think the issue is described here: https://googlechrome.github.io/samples/keyboardevent-code-attribute/, and could be fixed by making the keymaps use the new Chrome API.

**Comment by lee-dohm** [comment] 2018-04-05 16:58
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:58 UTC
Labels: bug
