### ISSUE TITLE
Throws error when deleting 2 paragraphs `d2ap`

### ISSUE THREAD

**Issue by zaz** [atom/vim-mode#741] opened 2015-07-06 03:18 UTC
### Steps to reproduce:
1. Open new file
2. Create 2 paragraphs
3. <kbd>ggd2ap</kbd> (go to beginning and attempt to delete 2 paragraphs)

**Expected behaviour**: The two paragraphs disappear.
**Actual behaviour**: Throws error.

The same problem occurs with <kbd>d2ip</kbd>, and <kbd>2dap</kbd> does not delete both paragraphs.

**Atom Version**: 0.200.0
**System**: linux 3.18.1-1-chromebook
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.54.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:263

TypeError: undefined is not a function
  at Repeat.Prefix.isLinewise (/home/zaz/.atom/packages/vim-mode/lib/prefixes.coffee:30:21)
  at Delete.Operator.setTextRegister (/home/zaz/.atom/packages/vim-mode/lib/operators/general-operators.coffee:51:17)
  at Delete.execute (/home/zaz/.atom/packages/vim-mode/lib/operators/general-operators.coffee:96:8)
  at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:266:23)
  at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:258:10)
  at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:258:10)
  at VimState.module.exports.VimState.pushOperations (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:224:8)
  at atom-text-editor.commands.(anonymous function) (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:196:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -0:40.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:39.7.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:31.2.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
  7x -0:31.1.0 blur (ul.list-inline.tab-bar.inset-panel)
     -0:21.7.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:15.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:11.7.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.7.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:08.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.5.0 vim-mode:select-around-paragraph (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:04.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:02.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.5.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.5.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:01.1.0 vim-mode:select-around-paragraph (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "foldingtext-for-atom",
      "run-in-atom",
      "coffee-lint",
      "markdown-preview"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.4.1
git-diff-details, v0.18.0
linter-coffeelint, v1.0.0
markdown-preview-plus, v1.5.0
mathjax-wrapper, v0.1.0
vim-mode, v0.54.0
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-07-07 00:03
@zaz can you try to upgrade to Atom 1.0.0 and see if you can still reproduce this?  Thanks.

**Comment by zaz** [comment] 2015-07-08 16:23
@50Wliu: Yes. The issue still occurs on Atom 1.0.0.

**Atom Version**: 1.0.0
**System**: "Arch Linux"
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.54.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:263

TypeError: undefined is not a function
    at Repeat.Prefix.isLinewise (/home/zaz/.atom/packages/vim-mode/lib/prefixes.coffee:37:34)
    at Delete.Operator.setTextRegister (/home/zaz/.atom/packages/vim-mode/lib/operators/general-operators.coffee:64:90)
    at Delete.execute (/home/zaz/.atom/packages/vim-mode/lib/operators/general-operators.coffee:137:14)
    at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:775:32)
    at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:762:23)
    at VimState.module.exports.VimState.processOpStack (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:762:23)
    at VimState.module.exports.VimState.pushOperations (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:725:28)
    at atom-text-editor.commands.(anonymous function) (/home/zaz/.atom/packages/vim-mode/lib/vim-state.coffee:691:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
```

### Commands

```
     -0:02.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:01.5.0 vim-mode:select-around-paragraph (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
```

**Config and installed packages same as above.**

**Comment by jacekkopecky** [comment] 2015-07-10 18:07
@50Wliu – I've reproduced it with a simple `d2ap` anywhere.

**Comment by lee-dohm** [comment] 2018-04-05 17:27
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:27 UTC
Labels: bug, uncaught-exception
