### ISSUE TITLE
ctrl-c and ctrl-v not working

### ISSUE THREAD

**Issue by Abukamel** [atom/vim-mode#541] opened 2015-02-25 09:43 UTC
I have tried to highlight text and use ctrl-c to copy and it does not work, also ctrl-v is not working in normal mode and i have to run it twice to work, don't know if this is the expected behavior or not.

but ctrl-c is not working neither in normal nor insert mode and to copy something i have to highlight it then right click and copy with mouse.

Regards

**Comment by maxbrunsfeld** [comment] 2015-02-25 19:29
@Abukamel can you report your OS, Atom version and vim-mode version? Thanks!

**Comment by Abukamel** [comment] 2015-02-25 21:04
@maxbrunsfeld 
* OS: manjaro linux
* Atom version: 0.182.0
* vim-mode version: 0.182.0

**Comment by doublemarked** [comment] 2015-02-27 11:05
I have similar problems, but it's been unclear whether it's by design or not. ^C and ^V only work in insert mode. If I'm not in insert mode I can right click on content and select Copy to copy, so it makes me think it's a key binding issue. 

* OS: Ubuntu 14.10
* Atom: 0.177.0
* vim-mode version: 0.34.0

**Comment by michaellenahan** [comment] 2015-03-01 13:36
* OS: Ubuntu 14.04
* Atom: 0.166.0
* vim-mode: 0.34

I was able to override the vim-mode `ctrl-c` keybinding by doing this:

* Go to your settings (`Edit > Preferences` or `ctrl-,`)
* On the left, click `Keybindings`

Here you can search for the keybindings, e.g. `ctrl-c`

* At the top, click the link to go to `your keymap file`

* Save the following to the keymap file (`~/.atom/keymap.cson`):

```
'atom-text-editor.vim-mode':
  'ctrl-c': 'core:copy'
```

* Restart Atom.

**Comment by Good4m** [comment] 2015-03-21 22:16
Thanks micaellenahan. This has been driving me nuts.

**Comment by steveoh** [comment] 2015-04-28 00:11
i fixed this but instead of `core:copy` i used `unset!`

**Comment by wil93** [comment] 2015-05-09 15:27
Thanks @michaellenahan, I used a slightly different version of your keymap.cson:

    'atom-text-editor.vim-mode.insert-mode':
        'ctrl-c': 'core:copy'

I think it's good to specify `.insert-mode` because:

1. In insert mode there's already ctrl-v to paste, so it makes sense to also have ctrl-c to copy
2. In visual mode I can already use `y`/`p`/`P`

**Comment by maxbrunsfeld** [comment] 2015-05-09 17:49
So it sounds like we just need to remove the `ctrl-c` binding in insert mode on windows and linux.

In normal mode, `ctrl-v` is used to enter visual mode (specifically visual-block mode, which is currently a [work in progress](https://github.com/atom/vim-mode/pull/658)), so I don't think we should remove that binding. If you want to paste, you should either enter insert mode, use `p`, or edit your `keymap.cson` to override vim-mode's `ctrl-v` binding.

Is everyone ok with that solution?

**Comment by h-kaseya** [comment] 2015-06-26 03:04
I am Windows user. And I want you to remove ctrl-c binding or enable to select it.

**Comment by danquirk** [comment] 2015-07-08 23:31
I'm having this same issue on Windows with the latest vim-mode (0.54.0) on the latest Atom (1.0.2). Whatever solution is chosen it needs to be overrideable by keymap.cson. At the moment I can't even seem to override this myself whether in normal or insert mode. I'm not sure why the user keymap isn't given priority 1 by Atom for precisely this reason. You can see I tried to manually override ctrl-c in keymap.cson and vim-mode is overriding both the core copy command and my user defined one:

![image](https://cloud.githubusercontent.com/assets/7121557/8584676/f02aa7d0-258d-11e5-83ec-2b3601eab7d7.png)

It's really annoying having to use the mouse to copy/paste any text out of Atom into something else.

**Comment by chrisvdb** [comment] 2015-07-09 02:10
I use "Packages -> Vim Mode -> Settings -> Use Clipboard As Default Register" and just use the standard Vi copy/paste commands to copy in/out of Atom. I would argue that this should be the default setting for Vim Mode.

**Comment by miloszw** [comment] 2015-07-10 14:55
I agree with @chrisvdb :+1: That would be the least confusing option.

**Comment by Abukamel** [comment] 2015-07-12 02:32
I agree with @chrisvdb :+1: That would be the least confusing option.

**Comment by DrBones** [comment] 2015-07-16 23:08
@danquirk I had the same issue with the user keybinding not taking precedence but I believe that was because a keybinding with a more specific context that has the same hotkey takes precedence over a more general one.

I think there is a better way - but since I am new to this - I kinda hacked my ctr-c with

    'atom-text-editor.vim-mode:not(.insert-mode)':
      'ctrl-c': 'core:copy'

Although I try to only use it as a crutch since @chrisvdb's hint is really how I think it should be done.

**Comment by danquirk** [comment] 2015-07-17 21:27
@DrBones good tip, thanks, might come in handy for some other commands. Changing the setting @chrisvdb mentioned seems like the easiest approach here (although for some reason I don't have Vim Mode listed in my Packages menu).

**Comment by morenoh149** [comment] 2015-12-17 08:59
should @chrisvdb suggestion be added to the readme? got here searching exactly for this issue

**Comment by morenoh149** [comment] 2015-12-17 22:44
@maxbrunsfeld you should reopen as I used githubs PR issue closing feature

**Comment by maxbrunsfeld** [comment] 2015-12-17 22:46
Oh, thanks for the heads up @morenoh149!

**Comment by oshliaer** [comment] 2016-02-04 17:46
@chrisvdb is right.
I would argue that this should be the default setting for Vim Mode too.

**Comment by morenoh149** [comment] 2016-02-05 00:16
@oshliaer have you seen https://github.com/atom/vim-mode/pull/940 ? the default is now different. However this issue still concerns a different issue.

**Comment by oshliaer** [comment] 2016-02-05 08:48
@morenoh149 , I see now, thanks.

**Comment by krokofant** [comment] 2016-09-26 16:16
Looking at [this SO answer](http://stackoverflow.com/a/9166363/3951400) I now do this
`Shift+V`
*select all lines to copy*
`y`
and then use `p` to paste

**Comment by notuxius** [comment] 2017-02-04 14:33
ctrl-x, ctrl-c and ctrl-v shortcuts not working in russian/ukrainian keyboard layouts in normal mode - but other shortcuts like ctrl-s, ctrl-p, ctrl-g... are working in these layouts in normal mode.
OS: Manjaro 16.10.3
Atom: 1.13.1

**Comment by kevincantu** [comment] 2017-08-18 20:59
Thanks @DrBones, your tip particularly helped me over on the -plus project:
```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'ctrl-c': 'core:copy'
```

**Comment by michaellenahan** [comment] 2017-08-22 15:30
This is what I ended up using with vim-mode-plus:

    'atom-text-editor.vim-mode-plus.insert-mode':
      'ctrl-c': 'unset!'

My rationale is this: when I am in insert mode and I make a selection, I want ctrl-c to copy. In other words, I want to unset the vim-mode-plus setting for ctrl-c.

The keybinding resolver is very helpful when trying to figure out these settings:
http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: more-information-needed
