### ISSUE TITLE
Start a new line at last indent

### ISSUE THREAD

**Issue by yeison** [atom/vim-mode#199] opened 2014-04-09 01:21 UTC
A feature request to start every new line at the last indent location.

**Comment by bronson** [comment] 2015-05-21 09:23
Atom already does this, doesn't it?  Can you give some steps to show where Atom gets this wrong?

**Comment by guywald1** [comment] 2016-11-30 19:03
Any news on this?

**Comment by bronson** [comment] 2016-11-30 19:51
It already does.  To reproduce: cmd-n to create a new file, hit tab, then hit return.  Your new line is at the same indent as the previous.  I also see this working in JS and Ruby.

Can you describe steps to reproduce a failure?

**Comment by bronson** [comment] 2016-11-30 19:52
There was this issue, but it was quite a while ago: https://github.com/atom/atom/issues/8013

**Comment by guywald1** [comment] 2016-11-30 19:58
Apologies, a new user to this Package and the problem was on my end. Thanks for the quick reply, amazing work regardless.

**Comment by bronson** [comment] 2016-11-30 20:04
You're welcome, glad it was an easy answer.

And, really, someone could close this issue.  :)

**Closed** 2016-11-30 20:20 UTC
Labels: enhancement
