### ISSUE TITLE
Search results aren't highlighted

### ISSUE THREAD

**Issue by shashurup** [atom/vim-mode#458] opened 2014-11-30 11:35 UTC
I'm very accustomed to \* to highlight all occurences of the word under cursor.

**Comment by bronson** [comment] 2015-05-16 00:31
You want :hlsearch.  Me too.  Anyone without :hlsearch in their .vimrc is really missing out.

This issue basically a dupe of https://github.com/atom/vim-mode/issues/493.  Once :incsearch is implemented (and I hope it is), :hlsearch is just an additional baby step.

**Comment by bronson** [comment] 2015-05-16 00:34
Also related, https://github.com/atom/vim-mode/pull/224 is a pull request that implemented :hlsearch but it wasn't future-proof.  Hoping someone revisits it.

**Comment by bedge** [comment] 2016-05-23 18:39
Agreed, without :hlsearch, vim-mode is a non-starter.

**Comment by trusktr** [comment] 2016-06-30 02:27
Made a quick hack: https://github.com/atom/vim-mode/pull/224#issuecomment-229543372

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: enhancement
