### ISSUE TITLE
Insert mode causes clipboard to be replaced by last delete action.

### ISSUE THREAD

**Issue by calvinl** [atom/vim-mode#289] opened 2014-05-30 20:11 UTC
![dd_bug_2](https://cloud.githubusercontent.com/assets/490687/3135535/ac68d888-e834-11e3-9b48-bd9afacfb030.gif)

As the gif shows, when you copy something to the clipboard using `y` or `d`, eg `yy`, `dd`, `d2d`, etc. Pasting with `p` works until you go into insert mode. Once you delete a character (using `backspace` or `delete`), and then go back into command mode (`esc`), `p` will then paste the last character or highlighted character that was deleted in insert mode. 

vim doesn't behave this way -- p will always keep its clipboard, insert mode doesn't change it.

**Comment by maxbrunsfeld** [comment] 2015-01-08 20:00
I can't reproduce this. Can you upgrade to the latest Atom and vim-mode release and try again? What OS are you on? Thanks!

**Comment by bronson** [comment] 2015-05-21 09:04
I can't reproduce either.  This is fixed?

**Comment by izuzak** [comment] 2015-09-09 12:25
Closing this because we're unable to reproduce and no other information was provided. Let us know if you can still reproduce this in the latest version of Atom.

**Closed by izuzak** 2015-09-09 12:25 UTC
Labels: more-information-needed
