### ISSUE TITLE
I want to  use 'rectangle' 

### ISSUE THREAD

**Issue by Kenji-Morita** [atom/vim-mode#850] opened 2015-08-29 03:47 UTC
How should I do?
could you  tell me how to cmd

**Comment by wolftune** [comment] 2015-08-29 21:54
I'm guessing you mean you want ctrl-V to work like it does in Vim, right?

**Comment by kenjimorita** [comment] 2015-08-30 21:26
other account this, thank you @wolftune 
yes, this like picture 
ctrV is..
![2015-08-31 6 20 48](https://cloud.githubusercontent.com/assets/9529003/9569509/bc1dee44-4fa8-11e5-994e-577a284fae97.png)


I want to know how to this
![2015-08-31 6 24 51](https://cloud.githubusercontent.com/assets/9529003/9569524/309b202a-4fa9-11e5-8852-b586521f11bc.png)

**Comment by wolftune** [comment] 2015-08-30 21:55
@kenjimorita you can already do that because Atom just supports it directly. It's not *identical* but it works in your case. The Ctrl-V option might still be nice (so this *could* stay open as an issue) as it is specifically a rectangle selection. However, just do Alt-Shift-downarrow in Atom to have multiple cursors, and that will work as you want for the example you do above. In some ways the multi-cursor mode in Atom is greatly superior to Vim's rectangle selection.

Cheers

**Comment by jacekkopecky** [comment] 2015-08-30 22:33
Would this be a duplicate of #468?

**Comment by jacekkopecky** [comment] 2015-08-30 22:35
@wolftune are you using a package to get the the alt-shift-arrow functionality? (I'm using `multi-cursor` with custom key mappings.)

**Comment by wolftune** [comment] 2015-08-30 23:59
@jacekkopecky Yes, this is a duplicate of #468 and can be closed, although maybe my notes about the alt-shift-arrow function should be added there. No, I am not using any package, the alt-shift-arrow function is built into Atom.

**Comment by 50Wliu** [comment] 2015-08-31 00:11
Thanks @jacekkopecky and @wolftune!  @kenjimorita, please subscribe to #468 for updates.

@wolftune, feel free to copy your comments to the other issue :)

**Closed by 50Wliu** 2015-08-31 00:11 UTC
