### ISSUE TITLE
Does not repeat inserts

### ISSUE THREAD

**Issue by cptaffe** [atom/vim-mode#580] opened 2015-03-14 01:09 UTC
Pressing `30i`, typing some characters, and then pressing `[esc]` should repeat that insert operation the expressed (in this case 30) number of times.

For example `3i#[esc]` should print `###`

Although other repeat operations work properly, this does not seem to work.

**Comment by scottmessinger** [comment] 2015-07-22 16:21
I can confirm.

**Comment by jacekkopecky** [comment] 2015-07-22 16:57
Indeed, #609 addresses this but needs a bit more work.

**Comment by lee-dohm** [comment] 2018-04-05 17:33
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:33 UTC
Labels: bug
