### ISSUE TITLE
Atom selection with Vim keybindings

### ISSUE THREAD

**Issue by adiospace** [atom/vim-mode#148] opened 2014-03-08 14:44 UTC
When I use Select Next (Cmd+D) or Select All (Ctrl+Cmd+G) and then some vim keybinding such as change word cw, to change all selected words (same happens with `x` or other vim keybindings) it changes the world + 1 char more.

![select-with-vim-bindings](https://f.cloud.github.com/assets/31248/2365575/15c80f2a-a6d0-11e3-9502-381c419d0d39.gif)

**Comment by agudulin** [comment] 2015-03-12 15:58
Seems to be fixed now.

**Comment by bronson** [comment] 2015-05-21 09:37
Agreed, I can't reproduce this.

**Comment by laughedelic** [comment] 2015-05-21 14:02
I have the same bug when using Vim `s` action, it always deletes 1 more character.

**Comment by lee-dohm** [comment] 2018-04-05 17:37
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:37 UTC
Labels: bug
