### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node.

### ISSUE THREAD

**Issue by chrisvdb** [atom/vim-mode#663] opened 2015-05-12 01:44 UTC
I have tried to reproduce the issue, but wasn't able to do so.

**Atom Version**: 0.198.0
**System**: linux 4.0.0-040000-generic
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.46.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /home/chrisvdb/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /home/chrisvdb/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/home/chrisvdb/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/home/chrisvdb/.atom/packages/vim-mode/lib/vim-state.coffee:209:18)
  at atom-text-editor.commands.(anonymous function) (/home/chrisvdb/.atom/packages/vim-mode/lib/vim-state.coffee:192:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:238:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at KeymapManager.module.exports.KeymapManager.terminatePendingState (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:502:14)

```

### Commands

```
 15x -0:38.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:28.6.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:27.5.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:26.4.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:26.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:24.8.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:24.8.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:24.8.0 editor:indent (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:23.8.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.4.0 vim-mode:mark (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:03.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.1.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.0 vim-mode:mark (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
  3x -0:01.0 blur (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:00.3.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.2.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "vim-mode": {
    "useSmartcaseForSearch": true,
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.14.0
go-plus, v3.3.10
language-jade, v0.4.0
language-javascript, v0.77.0
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-05-13 14:00
Thanks for the report! This looks like a duplicate of https://github.com/atom/vim-mode/issues/646 -- please subscribe there for updates.

**Closed by izuzak** 2015-05-13 14:00 UTC
Labels: uncaught-exception
