### ISSUE TITLE
Current line hangs on wrapped lines when moving in visual line mode

### ISSUE THREAD

**Issue by DepthDeluxe** [atom/vim-mode#688] opened 2015-05-31 16:55 UTC
When in visual line mode, I move past a soft-wrapped line (i.e. highlighting it) and try to move back past it, the current selected line hangs and I am unable to move past it.  Leaving visual line mode frees up the movement again.

```
Atom: v0.199.0
vim-mode: v0.49.0
OS: Linux
```

**Comment by bronson** [comment] 2015-07-05 22:23
Confirmed and, agreed, this is irritating.

**Comment by chibicode** [comment] 2015-07-27 20:28
Seems to be worked on at https://github.com/atom/vim-mode/pull/786

**Comment by bronson** [comment] 2015-07-29 22:49
Well, #786 needs a lot of work before it's ready.  Even then, it's only meant to make cursor navigation match Vim's, not to fix this visual line problem.  (but it would be nice if it did!)

**Comment by lee-dohm** [comment] 2018-04-05 17:28
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:28 UTC
Labels: bug
