### ISSUE TITLE
Undo doesn't group multiple character input

### ISSUE THREAD

**Issue by keyneston** [atom/vim-mode#55] opened 2014-02-27 08:13 UTC
When entering insert mode and then typing multiple characters 'u' will undo everything since entering insert mode.

atom currently will undo each character individually.

_edit_: Clarified first sentence.

**Comment by jacekkopecky** [comment] 2015-04-05 18:48
This seems resolved; could be closed? (just noticed)

**Comment by bronson** [comment] 2015-05-21 09:45
Agreed, is there anything left to implement?

**Comment by janbaykara** [comment] 2015-08-13 10:52
I've noticed that undo will often not group multiple changes by packages that are affected by a single command. Is this by design, or... ?

**Comment by jacekkopecky** [comment] 2015-08-13 11:11
@janbaykara can you please give an example?

**Comment by janbaykara** [comment] 2015-08-13 11:16
I remember https://atom.io/packages/autoclose-html + multiple cursors, then undoing, resulted in borks.

Also, https://atom.io/packages/atom-alignment cannot be undone - Undo simply ignores the fact that the plugin made changes.

**Comment by jacekkopecky** [comment] 2015-08-13 11:25
I don't use either of these packages so I need a bit more - any chance you could write down some steps to reproduce the problematic behaviour, please?

**Comment by lee-dohm** [comment] 2018-04-05 17:37
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 17:37 UTC
Labels: bug
