### ISSUE TITLE
Last character on line is skipped when selecting upward

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#806] opened 2015-07-31 06:40 UTC
I think there's an issue with #770.

When I'm in normal mode, and I click to the right of a line and drag upwards, the very last character on the line gets skipped.

![bug3](https://cloud.githubusercontent.com/assets/1776/9002061/41a4ac5e-3714-11e5-9047-5e84f3565ee1.gif)

gvim handles this correctly.

**Comment by bronson** [comment] 2015-07-31 06:41
cc @jacekkopecky

**Comment by bronson** [comment] 2015-07-31 07:32
If you double-click the last word on a line, the last character in the word doesn't get selected either.

**Comment by jacekkopecky** [comment] 2015-07-31 07:52
Interesting, thanks, definitely will look into it.

**Comment by bronson** [comment] 2015-07-31 09:17
Also: cmd-a to select all misses the last character in the file.  (when the file doesn't end with a newline)

**Comment by pirminis** [comment] 2015-08-16 14:51
+1 this is definately fresh new bug

**Comment by jacekkopecky** [comment] 2015-08-16 15:00
Yes, quite right, the problem is that vim-mode doesn't know the motion is
for selecting. I'm working on a solution.

**Comment by mcastilho** [comment] 2015-08-20 17:02
Do we have a fix for this ?

**Comment by jacekkopecky** [comment] 2015-08-20 18:38
yes, it's #827

**Comment by jacekkopecky** [comment] 2015-08-20 18:39
I'm very sorry indeed to have caused the regression.

**Comment by caleb** [comment] 2015-08-25 21:41
I think this might be related, so I closed my issue: https://github.com/atom/vim-mode/issues/842

It's exactly the same thing, but it sure seems like it might be in the same family :)

**Comment by mcastilho** [comment] 2015-08-26 13:15
@jacekkopecky Thanks.  How can I get this fix? Still doesn't show an update in Atom. Are you waiting for more changes to do a release? 0.58 still have this issue.

**Comment by jacekkopecky** [comment] 2015-08-26 13:30
@mcastilho the fix (#827) relies on functionality that will be released in Atom 1.0.8 which should be coming any day now, then vim-mode 0.59 should be released very briefly afterwards.

**Closed** 2015-08-28 02:38 UTC
Labels: bug
