### ISSUE TITLE
"dw" should not delete newline ('\n')

### ISSUE THREAD

**Issue by kaizhang** [atom/vim-mode#771] opened 2015-07-13 21:16 UTC
As in 0.55.0,  'dw' command deletes newline characters. If you use it to delete the last word of current line, it will append the next line to current line, which is very annoying.

**Comment by christopherdumas** [comment] 2015-07-14 14:09
Yes! I was just having a problem with that!

**Comment by ceres629** [comment] 2015-07-15 20:56
Also having an issue with this!

**Comment by jacekkopecky** [comment] 2015-07-15 22:24
duplicate of #550?

**Comment by 50Wliu** [comment] 2015-07-15 23:05
Thanks a lot @jacekkopecky :).

**Closed by 50Wliu** 2015-07-15 23:05 UTC
Labels: bug
