### ISSUE TITLE
shift submode from v to V clear selection(dont respect original selection)

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#864] opened 2015-09-18 04:42 UTC
Because in newest atom 1.0.12 include modification on `selection.selectLine()`

Old behavior -> selection.selectLine() dont clear old selection.
New behavior -> selection.selectLine() reset(clear) old selection.

In my opinion this breaking change should be reverted on atom core side.

The original patch is,

https://github.com/atom/atom/pull/8646

and modification by @nathansobo remove `range.union()`

https://github.com/atom/atom/commit/3ca11c2cef5f5d9d6fd51dc8ba9909af6237500d

So this change cause when selection.selectLine() called, original selection is cleared.

**Comment by nathansobo** [comment] 2015-09-21 20:08
@t9md Have you tried `Selection::expandOverLine`?

**Comment by t9md** [comment] 2015-09-22 01:55
@nathansobo 

I know `expandOverLine()`.
But I want method to select line which takes startRow and endRow as arguments.

I could workaround by using utility method like below
https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/utils.coffee#L20-L25

Before selection.selectLine() was changed, I used selection.selectLine() for this purpose like below
```coffeescript
for row in [startRow, endRow]
  selection.selectLine(row)
```

So I have already have workaround for this change, I don't have strong opinion to revert for now.

Thanks

**Comment by nathansobo** [comment] 2015-09-22 02:45
We could add an option to `selectLine`, but I found that behavior pretty surprising as a default and not matching the docs. What do you think? Sorry for the breakage I know it's frustrating.

**Comment by t9md** [comment] 2015-09-22 02:54
I understand the motivation to change this, so I think `selection.selectLine()` is OK as current implementation.

How about providing new `selection.selectBufferRowRange([startRow, endRow])` utility method?
Since when selecting whole line, atom put range [[startRow, 0], [startRow+1, 0]], so I frequently use getBufferRowRange to get startRow and endRow, Im happy if  I can pass rowRange to select  arbitrary row.

Here is example use case.
```coffeescript
[startRow, endRow] = selection.getBufferRowRange()
selection.selectBufferRowRange(startRow, endRow+10)
```

**Comment by skosch** [comment] 2015-09-26 17:49
If this isn't easily fixable in master right now (which I understand; thanks a million for your amazing work anyway!), would one of you mind explaining how to set up a local workaround in the meantime? "Completing the lines" by hitting Shift-V after making a rough selection is pretty common behaviour (at least for me it is) and so this regression is a bit annoying.

**Comment by jimmyye** [comment] 2015-09-26 18:05
Select Line (cmd-L) will do the job, see menu - Selection - Select Line
So I think binding Shift-V to this works:

menu - Atom - Open Your Keymap, add:
```
atom-text-editor.vim-mode.visual-mode':
  'shift-V': 'editor:select-line'
```

**Comment by skosch** [comment] 2015-09-26 18:07
Amazing! Thanks @jimmyye :)

**Comment by lee-dohm** [comment] 2018-04-05 16:58
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed by lee-dohm** 2018-04-05 16:58 UTC
